In [64]:
from sklearn import tree
import pandas as pd
import os

In [65]:
election = pd.read_csv(os.path.join("..", "Resources", "data_retrieval.csv"))
election.head()

,st_abbrev,district,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,...,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3,Industries_not_classified4,state_dist
0,AK,0,REP,1041380.0,1159940.0,151165.0,0.0,513967.0,41063.9,555031.0,...,193,1128,270,2633,569,2156,1823,40,NaN,AK_00
1,AL,1,REP,1325140.0,662806.0,1108650.0,0.0,264612.0,10105.0,274717.0,...,111,749,144,1427,198,1331,1663,21,NaN,AL_01
2,AL,2,REP,2506890.0,2100810.0,451536.0,0.0,741087.0,46129.8,787217.0,...,85,578,131,1538,159,1347,1673,29,NaN,AL_02
3,AL,3,REP,1219670.0,857764.0,887448.0,0.0,450890.0,9667.0,460557.0,...,47,521,89,1142,94,1186,1402,21,NaN,AL_03
4,AL,4,REP,1487010.0,853026.0,1099490.0,0.0,430365.0,23449.0,453814.0,...,76,401,58,1548,135,1060,1440,30,NaN,AL_04

In [66]:
df = election.drop(['id','st_abbrev', 'district', "Industries_not_classified4", "state_dist"], axis=1)

In [67]:
df.head()

,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,Other_Committee_Contribution,Party_Committee_Contribution,...,Real_estate_and_rental_and_leasing3,Professional__scientific__and_technical_services3,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3
0,REP,1041380.0,1159940.0,151165.0,0.0,513967.0,41063.9,555031.0,481912.0,0.00,...,933,1960,193,1128,270,2633,569,2156,1823,40
1,REP,1325140.0,662806.0,1108650.0,0.0,264612.0,10105.0,274717.0,985650.0,663.98,...,846,1420,111,749,144,1427,198,1331,1663,21
2,REP,2506890.0,2100810.0,451536.0,0.0,741087.0,46129.8,787217.0,1628590.0,5000.00,...,561,1249,85,578,131,1538,159,1347,1673,29
3,REP,1219670.0,857764.0,887448.0,0.0,450890.0,9667.0,460557.0,742720.0,11500.00,...,462,853,47,521,89,1142,94,1186,1402,21
4,REP,1487010.0,853026.0,1099490.0,0.0,430365.0,23449.0,453814.0,1020840.0,0.00,...,385,808,76,401,58,1548,135,1060,1440,30

In [68]:
target = df["party"]
target_names = ["negative", "positive"]

In [69]:

data = df.drop("party", axis=1)
feature_names = data.columns
data.head()

,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,Other_Committee_Contribution,Party_Committee_Contribution,Cand_Contribution,...,Real_estate_and_rental_and_leasing3,Professional__scientific__and_technical_services3,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3
0,1041380.0,1159940.0,151165.0,0.0,513967.0,41063.9,555031.0,481912.0,0.00,0.0,...,933,1960,193,1128,270,2633,569,2156,1823,40
1,1325140.0,662806.0,1108650.0,0.0,264612.0,10105.0,274717.0,985650.0,663.98,0.0,...,846,1420,111,749,144,1427,198,1331,1663,21
2,2506890.0,2100810.0,451536.0,0.0,741087.0,46129.8,787217.0,1628590.0,5000.00,0.0,...,561,1249,85,578,131,1538,159,1347,1673,29
3,1219670.0,857764.0,887448.0,0.0,450890.0,9667.0,460557.0,742720.0,11500.00,0.0,...,462,853,47,521,89,1142,94,1186,1402,21
4,1487010.0,853026.0,1099490.0,0.0,430365.0,23449.0,453814.0,1020840.0,0.00,0.0,...,385,808,76,401,58,1548,135,1060,1440,30

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [72]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [52]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=20)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8256880733944955

In [53]:
 sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.047907341751844315, '250_to_399'),
 (0.04515776937521011, '500_to_999a'),
 (0.04266156567569025, 'Housing_units_without_a_mortgage'),
 (0.037970116780786066, '1_500_to_1_999b'),
 (0.023685984307507173, 'Mining__quarrying__and_oil_and_gas_extraction1'),
 (0.022964961044644506, 'Public_transportation_excluding_taxicab'),
 (0.021056654970596368, 'Irish'),
 (0.019006866730144106, 'Less_than_50_000'),
 (0.018313353665120165, 'ScotchIrish'),
 (0.017954801373800035, 'Agriculture__forestry__fishing_and_hunting1'),
 (0.01686848019637896, 'Median_dollars2'),
 (0.016113214087596632, 'White'),
 (0.01605236057002089,
  'Agriculture__forestry__fishing_and_hunting__and_mining'),
 (0.015397615765094214, '2_500_to_2_999b'),
 (0.01532088523993141, 'Foreign_born'),
 (0.015138019672333403, '50_000_to_99_999'),
 (0.01499529732662214, 'Utilities3'),
 (0.014448613253307898, 'American'),
 (0.013174916645598573, 'Graduate_or_professional_degree'),
 (0.011737467132971142, 'Owneroccupied'),
 (0.011472447669446589, 'Born_in_United_States'),
 (0.010028156835542278, 'Manufacturing2'),
 (0.009985592319423038, 'Native'),
 (0.00986206010274708, 'Unemployed'),
 (0.00935967704612978, '400_to_599'),
 (0.008781669212277429, 'Moved_in_1979_and_earlier'),
 (0.008619746246708384, '500_000_to_999_999'),
 (0.008363810116311021, 'Russian'),
 (0.007942438461752589, 'Same_state'),
 (0.007709667839500734, 'Individual_Contribution'),
 (0.007403825773116493, 'Mining__quarrying__and_oil_and_gas_extraction3'),
 (0.007085452654882474, 'Agriculture__forestry__fishing_and_hunting3'),
 (0.0070396990900751496, 'Manufacturing1'),
 (0.006645674883054201, 'Educational_services1'),
 (0.006503457102501979, 'Ukrainian'),
 (0.006474122393767085, 'Individual_Unitemized_Contribution'),
 (0.006318604702030303, '1_000_to_1_499b'),
 (0.006233533771323287, '10_to_14_years'),
 (0.00611873865336132, '200_000_to_299_999'),
 (0.006087352122286281, 'Service_occupations'),
 (0.005936063309210959, '5_to_9_years'),
 (0.005897093934377281, 'Individual_Itemized_Contribution'),
 (0.005867529112231852, 'Professional__scientific__and_technical_services2'),
 (0.005851743715179033, 'Dutch'),
 (0.005792995573266646, 'Bachelor_s_degree'),
 (0.005558470575801141, 'Different_state1'),
 (0.005534683294025475, 'Renteroccupied'),
 (0.005387252399157343, 'Educational_services2'),
 (0.00528241174097706, 'Real_estate_and_rental_and_leasing2'),
 (0.0050279551051606855, '2_500_to_2_999a'),
 (0.005024022806382658, 'No_health_insurance_coverage2'),
 (0.0048221968261944245, 'Net_Contribution'),
 (0.004801709760636265, 'Median_dollars1'),
 (0.004794330712409809, 'German'),
 (0.004788842508649717, 'Black_or_African_American'),
 (0.004664444914865844, 'Less_than_500a'),
 (0.004561634193513633, 'Mexican'),
 (0.004518182823475275, 'Median_dollars3'),
 (0.0045117089103228775, 'Same_county'),
 (0.004401396866840096, '18_years_and_over2'),
 (0.004309754526385671,
  'Finance_and_insurance__and_real_estate_and_rental_and_leasing'),
 (0.004309153917366469, '300_000_to_499_999'),
 (0.004146979129617656, 'With_a_disability1'),
 (0.004014786965217951, 'Female'),
 (0.003970334510040019, 'Construction1'),
 (0.003965682539098102, 'Moved_in_1990_to_1999'),
 (0.003760754874728221, 'Under_18_years2'),
 (0.0037497315820430614,
  'Admin_and_support_and_waste_mngmt_and_remediation_services3'),
 (0.0036605857800149065, 'Other_Receipts'),
 (0.003609162641756411, 'Elementary_school_grades_18'),
 (0.003576594591404281, 'Retail_trade3'),
 (0.0035570166320274556, 'Information2'),
 (0.0035443925044685563, 'West_Indian_excluding_Hispanic_origin_groups'),
 (0.003515442068204832, 'With_a_disability2'),
 (0.0034728784778504393, 'Accommodation_and_food_services3'),
 (0.0034028730203248384, '50_000_to_74_999'),
 (0.0033329172239117758, '10_000_to_14_999'),
 (0.0032730513215121944, 'Related_children_of_the_householder_under_18_years'),
 (0.003263785799813748, 'Population_25_years_and_over'),
 (0.0032190775786477615, 'Puerto_Rican'),
 (0.0032081094872253558, 'Construction4'),
 (0.003132763125077281, '1_500_to_1_999a'),
 (0.003132247992863515, 'Other_services_except_public_administration3'),
 (0.0030690776635940767, 'Car__truck__or_van__drove_alone'),
 (0.0030650122225491135, 'State_of_residence'),
 (0.0030205397957619147, 'Italian'),
 (0.0030113744656932906, '60_to_64_years'),
 (0.002977481833031934, 'One_race'),
 (0.002975292933784477, 'Scottish'),
 (0.002963699091598289, 'Less_than_10_000'),
 (0.00296293888634491, 'Industries_not_classified1'),
 (0.002940856313041826, 'Moved_in_2000_to_2009'),
 (0.002795235059428958, 'Median_household_income_dollars'),
 (0.0027618029063989, 'All_families'),
 (0.002754848690955945, 'Different_house_in_the_US'),
 (0.002671468105028577, 'Wholesale_trade3'),
 (0.002670175841539319, 'Utilities2'),
 (0.0026639256360004035, 'Some_college__no_degree'),
 (0.0026392590583413267, 'Information3'),
 (0.0025298913338843943, 'All_people'),
 (0.00252292145967723,
  'With_related_children_of_the_householder_under_5_years_only3'),
 (0.002496451284773419, 'Male'),
 (0.0024645870704609776, 'American_Indian_and_Alaska_Native'),
 (0.0024210104722424066, 'Civilian_veterans'),
 (0.0024009813761570195, '65_years_and_over3'),
 (0.0023190806872110145, '35_to_44_years'),
 (0.0023151587803788057, '150_000_to_199_000'),
 (0.002297606933143165, 'Married_couple_families'),
 (0.0022676518817049524, 'Agriculture__forestry__fishing_and_hunting2'),
 (0.0022436258124165272, 'Rental_vacancy_rate'),
 (0.0022259385389868367, 'Transportation_and_warehousing2'),
 (0.00220410099611113, '150_000_to_199_999'),
 (0.0022026532977346583, 'Some_other_race'),
 (0.0021745988185510627, '65_years_and_over1'),
 (0.002171160747597136, 'Individual_Refund'),
 (0.0021409846487659826, '1_000_or_more'),
 (0.0021403642063307876, 'Car__truck__or_van__carpooled'),
 (0.002120254397101773, 'Professional__scientific__and_technical_services1'),
 (0.002100344013574422, 'Abroad'),
 (0.0020819021262295395, 'Management_of_companies_and_enterprises1'),
 (0.002041462984982601, 'Population_1_year_and_over'),
 (0.002005672618444046, 'Arab'),
 (0.0018542420505967092, 'Educational_services3'),
 (0.0017958250586298454, 'French_Canadian'),
 (0.0017742166250993036, 'Population_3_years_and_over_enrolled_in_school'),
 (0.0017740812399685197, 'No_health_insurance_coverage1'),
 (0.0017727180099238096, 'Occupied_housing_units'),
 (0.0017658493001747322, 'Total_for_all_sectors2'),
 (0.001756803053554083, 'Cash_On_Hand_COP'),
 (0.001743971222532743, 'Total_Contribution_Refund'),
 (0.0017210820895510038, '75_000_to_99_999'),
 (0.001710325603109461, 'Wholesale_trade1'),
 (0.0016428311447894985, 'Moved_in_1980_to_1989'),
 (0.0016198302689710569, 'Less_than_500b'),
 (0.0015859135045020005, 'Associate_s_degree'),
 (0.001538957680450457, 'Other_services_except_public_administration1'),
 (0.0015380026931042356, 'Hungarian'),
 (0.0015135842939223523, 'Czech'),
 (0.0015028440814807574, 'Finance_and_insurance1'),
 (0.0014672176485921726, 'Unemployment_Rate'),
 (0.0014393970464080337, 'Same_house'),
 (0.0013798141040337038, 'Average_household_size_of_renteroccupied_unit'),
 (0.0013784971412090054, 'Less_than_9th_grade'),
 (0.0013713369480368783, 'Worked_at_home'),
 (0.001366558984364128, 'Two_or_more_races'),
 (0.0013590938610636466, 'Total_Disbursement'),
 (0.001356978835085296, 'Walked'),
 (0.0013320352940541524,
  'Admin_and_support_and_waste_mngmt_and_remediation_services2'),
 (0.0013015853695824483, 'Less_than_250'),
 (0.001270085940594464, '200_000_or_more'),
 (0.0012501301138302095, 'Native_Hawaiian_and_Other_Pacific_Islander'),
 (0.0012440141699074148, 'Information1'),
 (0.0012420698616525264, 'Swedish'),
 (0.0011737498091666677, 'Norwegian'),
 (0.001170926011791416, 'Cash_On_Hand_BOP'),
 (0.001161128661416611, 'Percent_bachelor_s_degree_or_higher'),
 (0.0011352609527609317, 'Occupied_units_paying_rent'),
 (0.0011336868041848906, 'Accommodation_and_food_services1'),
 (0.0011174488985990479, '20_to_24_years'),
 (0.0011024313349894746, 'Operating_Expenditure'),
 (0.0010831617331968385, 'Transportation_and_warehousing3'),
 (0.0010809120902511712, 'Finance_and_insurance3'),
 (0.0010736492080652023, 'Mean_travel_time_to_work_minutes'),
 (0.001063412080361233,
  'Selfemployed_in_own_not_incorporated_business_workers'),
 (0.0010515349174302431, 'Industries_not_classified2'),
 (0.0010386386752368223, 'With_private_health_insurance'),
 (0.0010362290578573702, 'Percent_high_school_graduate_or_higher'),
 (0.0010202159718734304, 'French_except_Basque'),
 (0.0010083131854026091, 'Not_in_labor_force'),
 (0.0009975445058317983, 'Portuguese'),
 (0.0009942964265809684, 'Manufacturing4'),
 (0.0009932052757270072, 'Polish'),
 (0.0009913272716454418, 'Transportation_and_warehousing1'),
 (0.0009904761904761903, 'High_school_graduate_includes_equivalency'),
 (0.0009686153729463164, '18_to_64_years'),
 (0.0009660543368408536, 'Retail_trade4'),
 (0.0009488840235966668, 'Civilian_population_18_years_and_over'),
 (0.000933368044896032, 'Retail_trade1'),
 (0.00092981488863935, 'College_or_graduate_school'),
 (0.0009237853407109831,
  'With_related_children_of_the_householder_under_18_years1'),
 (0.0009141788820876664, '25_000_to_34_999'),
 (0.0008928398490381583, 'Other_services_except_public_administration2'),
 (0.0008817280981089165, 'Swiss'),
 (0.0008797955625818885, '55_to_59_years'),
 (0.0008635941136716414, 'Public_administration'),
 (0.0008468906772637043, 'With_public_coverage'),
 (0.0008412279339441945, 'Moved_in_2010_to_2014'),
 (0.0008380392460225367, 'Unrelated_individuals_15_years_and_over'),
 (0.0008190067107539485, 'Not_Hispanic_or_Latino'),
 (0.0007892143508194853, 'Real_estate_and_rental_and_leasing1'),
 (0.000771416479879301, '15_to_19_years'),
 (0.0007698211172591525, 'Total_civilian_noninstitutionalized_population'),
 (0.000724594052180259, 'Accommodation_and_food_services2'),
 (0.0007013984806629834, 'Total_Contribution'),
 (0.0006734839183800863,
  'With_related_children_of_the_householder_under_5_years_only2'),
 (0.0006323478706300393, '45_to_54_years'),
 (0.0006309209504581459, 'Mean_household_income_dollars'),
 (0.0006226053639846742, 'Total_for_all_sectors3'),
 (0.0006166885192302547, '100_000_to_149_999a'),
 (0.0006134312278380067, 'Arts__entertainment__and_recreation1'),
 (0.0006121676054585639, 'Different_county'),
 (0.0006098991320666199, 'Different_state2'),
 (0.0006060819547127275, 'Industries_not_classified3'),
 (0.0006033882571362264, '1_000_to_1_499a'),
 (0.0006031489463601533, 'Hispanic_or_Latino_of_any_race'),
 (0.0006015260252548384, 'Cand_Loan_Repayment'),
 (0.0005979122415839259, 'Danish'),
 (0.0005972971019258649, 'Party_Committee_Contribution'),
 (0.000583834083335579, 'Other_means'),
 (0.0005805799647505033, '9th_to_12th_grade__no_diploma'),
 (0.0005803423382056581, 'Related_children_of_the_householder_5_to_17_years'),
 (0.0005766949552098057, 'Median_age_years'),
 (0.000576067274169534, 'Other_Hispanic_or_Latino'),
 (0.0005740155666056272,
  'With_related_children_of_the_householder_under_18_years2'),
 (0.0005715098731328012, '35_000_to_49_999'),
 (0.0005678514749225394, 'Welsh'),
 (0.0005336617405582924, 'Related_children_of_the_householder_under_5_years'),
 (0.000531362485350745, 'Private_wage_and_salary_workers'),
 (0.0005306122448979592, 'Born_in_PR__US_Is_areas_or_abroad_to_US_parents'),
 (0.000529281480033874, 'Under_5_years'),
 (0.0005278773375491332,
  'Production__transportation__and_material_moving_occupations'),
 (0.0005188378033205621, '15_000_to_24_999'),
 (0.000517529109021886, 'Transfer_From_Other_Auth_Committee'),
 (0.0004980842911877394, 'Average_household_size_of_owneroccupied_unit'),
 (0.0004952380952380951, '18_years_and_over1'),
 (0.0004926855150458575,
  'Civilian_noninstitutionalized_population_under_19_years'),
 (0.0004797900263815892, '65_years_and_over2'),
 (0.0004731907128436094, 'Greek'),
 (0.0004652427851580394, 'Workers_16_years_and_over'),
 (0.000450911530322434, 'Transportation_and_warehousing__and_utilities1'),
 (0.0004314004770231988, 'Nursery_school__preschool'),
 (0.00042061396697209725, 'Offsets_To_Operating_Expenditure'),
 (0.0004156435440965827, 'Under_18_years1'),
 (0.0003722485251758567, '65_to_74_years'),
 (0.00033241812544695313, 'Other_Committee_Contribution'),
 (0.0003167641325536062, '25_to_34_years'),
 (0.00031546047522907294,
  'With_related_children_of_the_householder_under_18_years3'),
 (0.00030792844690366095, 'Health_care_and_social_assistance3'),
 (0.0003054350286164269, 'Manufacturing3'),
 (0.00030300751879699337, 'Arts__entertainment__and_recreation2'),
 (0.0002989490235021491, 'Total_Receipt'),
 (0.000285754936566401, 'Construction3'),
 (0.0002727182889636027, 'Health_care_and_social_assistance1'),
 (0.00018423566292243089, 'Vacant_housing_units'),
 (0.00014922926735873876, 'Cand_Loan'),
 (7.423199081858901e-05, 'Unpaid_family_workers'),
 (0.0, 'With_related_children_of_the_householder_under_5_years_only1'),
 (0.0, 'With_health_insurance_coverage'),
 (0.0, 'With_a_disability4'),
 (0.0, 'With_a_disability3'),
 (0.0, 'Wholesale_trade4'),
 (0.0, 'Wholesale_trade2'),
 (0.0, 'Utilities1'),
 (0.0, 'Transfer_To_Other_Auth_Committee'),
 (0.0, 'Total_population'),
 (0.0, 'Total_housing_units'),
 (0.0, 'Total_for_all_sectors1'),
 (0.0, 'Total_Loan_Repayment'),
 (0.0, 'Total_Loan'),
 (0.0, 'Subsaharan_African'),
 (0.0, 'Slovak'),
 (0.0, 'Sales_and_office_occupations'),
 (0.0, 'Retail_trade2'),
 (0.0, 'Real_estate_and_rental_and_leasing3'),
 (0.0, 'Professional__scientific__and_technical_services3'),
 (0.0, 'Prof__scientific__and_mngmnt__and_admin_and_waste_mngmnt_ser'),
 (0.0, 'Population_16_years_and_over'),
 (0.0, 'People_in_families'),
 (0.0, 'Party_Committee_Refund'),
 (0.0, 'Other_services__except_public_administration'),
 (0.0, 'Other_Loan_Repayment'),
 (0.0, 'Other_Loan'),
 (0.0, 'Other_Disbursements'),
 (0.0, 'Other_Committee_Refund'),
 (0.0, 'Offsets_To_Leagal_Accounting'),
 (0.0, 'Offsets_To_Fundraising'),
 (0.0, 'No_rent_paid'),
 (0.0, 'Net_Operating_Expenditure'),
 (0.0, 'Natural_resources__construction__and_maintenance_occupations'),
 (0.0, 'Moved_in_2015_or_later'),
 (0.0, 'Mining__quarrying__and_oil_and_gas_extraction2'),
 (0.0, 'Median_dollars4'),
 (0.0, 'Management_of_companies_and_enterprises3'),
 (0.0, 'Management_of_companies_and_enterprises2'),
 (0.0, 'Management__business__science__and_arts_occupations'),
 (0.0, 'Lithuanian'),
 (0.0, 'Kindergarten'),
 (0.0, 'Information4'),
 (0.0, 'In_labor_force'),
 (0.0, 'Housing_units_with_a_mortgage'),
 (0.0, 'Homeowner_vacancy_rate'),
 (0.0, 'High_school_grades_912'),
 (0.0, 'Health_care_and_social_assistance2'),
 (0.0, 'Government_workers'),
 (0.0, 'Fundraising_Disbursement'),
 (0.0, 'Finance_and_insurance2'),
 (0.0, 'Families_with_female_householder__no_husband_present'),
 (0.0, 'Exempt_Legal_Accounting_Disbursement'),
 (0.0, 'English'),
 (0.0, 'Employed'),
 (0.0, 'Educational_services__and_health_care_and_social_assistance'),
 (0.0, 'Debt_Owed_By_Committee'),
 (0.0, 'Debt_Owe_To_Committee'),
 (0.0, 'Cuban'),
 (0.0, 'Construction2'),
 (0.0, 'Civilian_labor_force'),
 (0.0, 'Cand_Contribution'),
 (0.0, 'Asian'),
 (0.0, 'Arts__entertainment__and_recreation3'),
 (0.0, 'Arts_Entmt_and_recreation_and_accommodation_and_food_services'),
 (0.0, 'Armed_Forces'),
 (0.0, 'Admin_and_support_and_waste_mngmt_and_remediation_services1'),
 (0.0, '85_years_and_over'),
 (0.0, '800_to_999'),
 (0.0, '75_to_84_years'),
 (0.0, '600_to_799'),
 (0.0, '500_to_999b'),
 (0.0, '3_000_or_more2'),
 (0.0, '3_000_or_more1'),
 (0.0, '2_000_to_2_499b'),
 (0.0, '2_000_to_2_499a'),
 (0.0, '1_000_000_or_more'),
 (0.0, '100_000_to_149_999b')]

[(0.058985033306369936, 'Public_transportation_excluding_taxicab'), (0.05363083135079348, 'Foreign_born'), (0.0377943902953491, 'Born_in_United_States'), (0.03170276382718641, 'Less_than_250'), (0.02990366159470927, '400_to_599'), (0.022142544066125966, '500_to_999a'), (0.021766116909306528, 'Housing_units_without_a_mortgage'), (0.019541834681959046, 'American'), (0.017272436210601615, 'Agriculture__forestry__fishing_and_hunting2'), (0.016765124456656972, '1_000_to_1_499a'), (0.016476507614901503, '50_000_to_74_999'), (0.01635545048961632, '50_000_to_99_999'), (0.01624786684572141, 'Civilian_veterans'), (0.01455194320512294, 'Less_than_500a'), (0.014469412478834376, '2_500_to_2_999a'), (0.014147755160758302, 'Occupied_units_paying_rent'), (0.013577819313344324, 'Renteroccupied'), (0.012669475287774012, 'Dutch'), (0.012534509859784113, 'ScotchIrish'), (0.011601891561221387, 'Service_occupations'), (0.010886445281122776, 'Educational_services1'), (0.010575143204451822, 'Educational_services2'), (0.010473243543246007, '65_years_and_over3'), (0.010076778263329386, 'Walked'), (0.009261548889688774, 'Individual_Unitemized_Contribution'), (0.008739793841475808, 'Elementary_school_grades_18'), (0.0086169359737303, 'No_health_insurance_coverage2'), (0.008303987070239476, '150_000_to_199_999'), (0.008293900999305628, 'Construction1'), (0.00809910935815963, 'German'), (0.0080596857792245, 'With_private_health_insurance'), (0.007605471052104443, 'Agriculture__forestry__fishing_and_hunting3'), (0.007348690284418299, 'Less_than_50_000'), (0.0073063417521865865, 'Scottish'), (0.0072053501227987175, 'Mining__quarrying__and_oil_and_gas_extraction3'), (0.007123486933869069, 'Mining__quarrying__and_oil_and_gas_extraction2'), (0.007054522859113818, 'Agriculture__forestry__fishing_and_hunting__and_mining'), (0.006934461227572121, '18_years_and_over1'), (0.006728013032132875, 'Other_Committee_Contribution'), (0.006527957083177998, 'Car__truck__or_van__drove_alone'), (0.006524594276471599, 'Italian'), (0.0060918981923011204, 'Unemployment_Rate'), (0.005931793476605791, 'White'), (0.005877849715663914, 'Czech'), (0.005715280383229769, 'Real_estate_and_rental_and_leasing1'), (0.00546088422096133, 'Moved_in_1979_and_earlier'), (0.005396976993398071, 'Mining__quarrying__and_oil_and_gas_extraction1'), (0.005364306308015933, '2_500_to_2_999b'), (0.0053185415587517675, 'Under_18_years2'), (0.004847040080827716, 'Native'), (0.00484348531200089, 'Portuguese'), (0.004802009302169823, 'Arab'), (0.004360786385882645, 'Moved_in_1990_to_1999'), (0.004330182243603506, 'Total_Contribution'), (0.004298810320998519, 'Total_for_all_sectors1'), (0.004289843344612347, '250_to_399'), (0.004236356717926483, 'Median_dollars4'), (0.004214954222579255, 'Utilities2'), (0.004204002598335053, 'Individual_Itemized_Contribution'), (0.004187665761942369, 'Civilian_noninstitutionalized_population_under_19_years'), (0.004149026980973532, 'Health_care_and_social_assistance1'), (0.004136400194484925, '500_to_999b'), (0.004017868551764767, 'High_school_grades_912'), (0.003963761123964333, '75_to_84_years'), (0.003789658557739782, 'Median_dollars3'), (0.0037788581008533794, 'Related_children_of_the_householder_5_to_17_years'), (0.0037694239089632944, 'Related_children_of_the_householder_under_18_years'), (0.0037124926948644893, 'Armed_Forces'), (0.003700770060324947, 'Asian'), (0.0036516199799608564, 'Individual_Contribution'), (0.0035280473864644974, '5_to_9_years'), (0.003392006852106585, 'Real_estate_and_rental_and_leasing2'), (0.0033086786892118315, 'Manufacturing1'), (0.0032266921361044634, 'With_related_children_of_the_householder_under_5_years_only1'), (0.00321665082221458, '65_years_and_over1'), (0.0031780355375586114, 'Health_care_and_social_assistance3'), (0.0031481416622653963, 'All_people'), (0.0031460407583017826, 'Graduate_or_professional_degree'), (0.0031261885389880007, 'Associate_s_degree'), (0.0031160867862035637, 'Welsh'), (0.0029300346680538767, 'Moved_in_2015_or_later'), (0.002918424628546789, 'Total_population'), (0.0029036681218827876, 'Hispanic_or_Latino_of_any_race'), (0.002892789898459711, 'Unrelated_individuals_15_years_and_over'), (0.0028378746987730886, 'All_families'), (0.00283021856853867, '45_to_54_years'), (0.0028215777602066837, 'With_a_disability1'), (0.0028030860208176954, '10_to_14_years'), (0.0027860855147666015, 'Cash_On_Hand_BOP'), (0.002770801015839242, 'Other_Disbursements'), (0.002748839894077521, 'Operating_Expenditure'), (0.0027016826586826774, 'Cuban'), (0.002663962193177642, '150_000_to_199_000'), (0.0026582692679986385, 'Selfemployed_in_own_not_incorporated_business_workers'), (0.002648972279352272, '35_to_44_years'), (0.002631487750959291, 'Management_of_companies_and_enterprises1'), (0.002605328470678235, '100_000_to_149_999a'), (0.002590843696051966, 'Not_in_labor_force'), (0.0025452048578385495, 'Greek'), (0.0025427974123028276, 'Ukrainian'), (0.0025124008438652057, 'Other_Committee_Refund'), (0.0024664306204152785, 'Abroad'), (0.0024407996056186056, 'Information1'), (0.0023919715553689545, 'With_related_children_of_the_householder_under_5_years_only3'), (0.002364917471192775, 'Same_county'), (0.0023646158061263033, 'Subsaharan_African'), (0.0023518075343207296, 'Irish'), (0.002296056542725822, 'No_health_insurance_coverage1'), (0.0021894189312777626, 'West_Indian_excluding_Hispanic_origin_groups'), (0.0021538748987938302, 'Government_workers'), (0.002142554127570645, 'Lithuanian'), (0.0020946028265107215, 'Polish'), (0.002086143201746226, 'Moved_in_2010_to_2014'), (0.0020790800143026867, 'Different_county'), (0.0020762061904977293, 'Moved_in_2000_to_2009'), (0.0020612613812861363, '2_000_to_2_499b'), (0.002024936178152228, 'Occupied_housing_units'), (0.002022107039649077, 'Other_services__except_public_administration'), (0.002013339603138454, 'Other_Hispanic_or_Latino'), (0.001983684314274739, '20_to_24_years'), (0.0019750527182066935, 'Finance_and_insurance3'), (0.001963983809513644, 'Worked_at_home'), (0.001961424397374953, 'Unemployed'), (0.0019097258959296936, 'Kindergarten'), (0.0018849363303714492, 'Average_household_size_of_renteroccupied_unit'), (0.0018779030466192655, 'Arts__entertainment__and_recreation1'), (0.0018622792615369493, 'Information3'), (0.0018575548088492256, 'Housing_units_with_a_mortgage'), (0.0018554464489609502, 'American_Indian_and_Alaska_Native'), (0.0018167714696408072, 'Utilities3'), (0.0017791037953828505, 'Cash_On_Hand_COP'), (0.001775332624932022, 'Total_Contribution_Refund'), (0.0017471627365916464, 'Other_services_except_public_administration3'), (0.0017278043593833066, '75_000_to_99_999'), (0.0017102767772949217, 'Retail_trade1'), (0.0016658079860254916, 'Cand_Loan_Repayment'), (0.0016565426158117445, '15_to_19_years'), (0.0016534211401008705, 'Black_or_African_American'), (0.0016341528504161661, 'With_health_insurance_coverage'), (0.0016220736509265769, 'Industries_not_classified1'), (0.0015724639784790158, 'Retail_trade2'), (0.0015403711500083103, 'Homeowner_vacancy_rate'), (0.0015309844952234846, 'Educational_services__and_health_care_and_social_assistance'), (0.001528947416863977, 'Population_3_years_and_over_enrolled_in_school'), (0.0015240082410862862, 'Vacant_housing_units'), (0.0014491152032660574, 'Same_state'), (0.0014360622818097672, 'Real_estate_and_rental_and_leasing3'), (0.0014291076791076792, 'Professional__scientific__and_technical_services1'), (0.0014120142966296812, 'Percent_high_school_graduate_or_higher'), (0.0013968139574624685, 'Nursery_school__preschool'), (0.0013802639774739545, 'Different_state2'), (0.0013204029082922425, '65_years_and_over2'), (0.0013176383403508598, 'Individual_Refund'), (0.0013119224173580046, 'Industries_not_classified2'), (0.0013099764109229099, 'Employed'), (0.0013065647621105796, 'Transportation_and_warehousing__and_utilities1'), (0.001292364715328113, 'Russian'), (0.0012722821953540203, '500_000_to_999_999'), (0.0012538703212576145, 'Population_16_years_and_over'), (0.0012393227577791337, '25_to_34_years'), (0.0011983345984240572, 'Total_civilian_noninstitutionalized_population'), (0.0011739789930349375, 'Accommodation_and_food_services2'), (0.0011620423340961104, 'Different_state1'), (0.001145336826713098, 'Not_Hispanic_or_Latino'), (0.0011369024945778496, '800_to_999'), (0.001127256681163637, '200_000_or_more'), (0.0011203217843275917, 'Some_other_race'), (0.0010788232281988806, 'Median_dollars2'), (0.0010634852576266235, 'Admin_and_support_and_waste_mngmt_and_remediation_services2'), (0.001036325603938675, 'Total_housing_units'), (0.0009820793146688843, 'Sales_and_office_occupations'), (0.0009817701675103416, '1_000_to_1_499b'), (0.000980896364224627, 'Total_Disbursement'), (0.0009684972328650487, 'Puerto_Rican'), (0.0009620833439056776, '100_000_to_149_999b'), (0.0009277232244804751, 'French_Canadian'), (0.0009096090500265074, 'Other_means'), (0.0008963044677330389, 'Bachelor_s_degree'), (0.0008960649471360775, 'Public_administration'), (0.0008947843707325667, 'People_in_families'), (0.0008909088108106147, 'Mexican'), (0.000876503056019641, 'Median_dollars1'), (0.0008416781767955798, 'Finance_and_insurance2'), (0.000803373675051416, 'Civilian_population_18_years_and_over'), (0.0007602339181286549, '65_to_74_years'), (0.0007424663708061527, '1_500_to_1_999b'), (0.0007224348768057464, 'Wholesale_trade2'), (0.0006971190512507627, '200_000_to_299_999'), (0.0006774744234953603, 'Swedish'), (0.000650608022770371, 'Admin_and_support_and_waste_mngmt_and_remediation_services3'), (0.0006355675426188252, '3_000_or_more1'), (0.0006217953623632049, 'Other_Receipts'), (0.0006158165608020214, 'Hungarian'), (0.0006140026409571089, 'With_a_disability4'), (0.0006018170696179363, 'Construction4'), (0.0006013240210695282, 'Different_house_in_the_US'), (0.0005987626677281843, 'Norwegian'), (0.0005985885759388304, 'No_rent_paid'), (0.0005983020856906454, 'Construction3'), (0.0005883488818354075, 'Transfer_From_Other_Auth_Committee'), (0.0005861015095592393, 'Swiss'), (0.000581900961735216, 'Transfer_To_Other_Auth_Committee'), (0.000574609323097295, 'State_of_residence'), (0.0005703755703755704, 'Percent_bachelor_s_degree_or_higher'), (0.0005697887157846109, 'Party_Committee_Refund'), (0.0005611187845303868, 'Private_wage_and_salary_workers'), (0.0005596158261268846, 'Manufacturing2'), (0.0005547337278106511, 'Natural_resources__construction__and_maintenance_occupations'), (0.0005534269902085995, '60_to_64_years'), (0.0005393244575936884, 'Party_Committee_Contribution'), (0.0005219575495939972, 'Net_Operating_Expenditure'), (0.0005136423405654176, 'Accommodation_and_food_services1'), (0.0005127516741933344, 'High_school_graduate_includes_equivalency'), (0.00048202420503084967, 'Wholesale_trade1'), (0.0004751461988304094, 'Population_25_years_and_over'), (0.00046577619811969735, 'Car__truck__or_van__carpooled'), (0.00046577619811969735, 'Arts_Entmt_and_recreation_and_accommodation_and_food_services'), (0.00046386161224023755, 'Less_than_10_000'), (0.0004622781065088758, 'Two_or_more_races'), (0.00043176548204463324, '18_years_and_over2'), (0.00042846596002742187, 'With_related_children_of_the_householder_under_18_years3'), (0.00041113219481340925, 'Some_college__no_degree'), (0.00041091387245233407, 'Agriculture__forestry__fishing_and_hunting1'), (0.00036238834127016236, 'With_public_coverage'), (0.0003335895129721414, 'Finance_and_insurance__and_real_estate_and_rental_and_leasing'), (0.00031173265807243704, 'Information4'), (0.00030621509576181084, '2_000_to_2_499a'), (0.0003061473694003807, 'Median_age_years'), (0.00030105973025048297, 'Under_5_years'), (0.0002949183303085294, 'Management_of_companies_and_enterprises2'), (0.00011797706459862917, 'Slovak'), (0.00011704819397126976, 'With_a_disability2'), (5.1332067142342354e-05, 'Born_in_PR__US_Is_areas_or_abroad_to_US_parents'), (0.0, 'Workers_16_years_and_over'), (0.0, 'With_related_children_of_the_householder_under_5_years_only2'), (0.0, 'With_related_children_of_the_householder_under_18_years2'), (0.0, 'With_related_children_of_the_householder_under_18_years1'), (0.0, 'With_a_disability3'), (0.0, 'Wholesale_trade4'), (0.0, 'Wholesale_trade3'), (0.0, 'Utilities1'), (0.0, 'Unpaid_family_workers'), (0.0, 'Under_18_years1'), (0.0, 'Transportation_and_warehousing3'), (0.0, 'Transportation_and_warehousing2'), (0.0, 'Transportation_and_warehousing1'), (0.0, 'Total_for_all_sectors3'), (0.0, 'Total_for_all_sectors2'), (0.0, 'Total_Receipt'), (0.0, 'Total_Loan_Repayment'), (0.0, 'Total_Loan'), (0.0, 'Same_house'), (0.0, 'Retail_trade4'), (0.0, 'Retail_trade3'), (0.0, 'Rental_vacancy_rate'), (0.0, 'Related_children_of_the_householder_under_5_years'), (0.0, 'Professional__scientific__and_technical_services3'), (0.0, 'Professional__scientific__and_technical_services2'), (0.0, 'Prof__scientific__and_mngmnt__and_admin_and_waste_mngmnt_ser'), (0.0, 'Production__transportation__and_material_moving_occupations'), (0.0, 'Population_1_year_and_over'), (0.0, 'Owneroccupied'), (0.0, 'Other_services_except_public_administration2'), (0.0, 'Other_services_except_public_administration1'), (0.0, 'Other_Loan_Repayment'), (0.0, 'Other_Loan'), (0.0, 'One_race'), (0.0, 'Offsets_To_Operating_Expenditure'), (0.0, 'Offsets_To_Leagal_Accounting'), (0.0, 'Offsets_To_Fundraising'), (0.0, 'Net_Contribution'), (0.0, 'Native_Hawaiian_and_Other_Pacific_Islander'), (0.0, 'Moved_in_1980_to_1989'), (0.0, 'Median_household_income_dollars'), (0.0, 'Mean_travel_time_to_work_minutes'), (0.0, 'Mean_household_income_dollars'), (0.0, 'Married_couple_families'), (0.0, 'Manufacturing4'), (0.0, 'Manufacturing3'), (0.0, 'Management_of_companies_and_enterprises3'), (0.0, 'Management__business__science__and_arts_occupations'), (0.0, 'Male'), (0.0, 'Less_than_9th_grade'), (0.0, 'Less_than_500b'), (0.0, 'Information2'), (0.0, 'Industries_not_classified3'), (0.0, 'In_labor_force'), (0.0, 'Health_care_and_social_assistance2'), (0.0, 'Fundraising_Disbursement'), (0.0, 'French_except_Basque'), (0.0, 'Finance_and_insurance1'), (0.0, 'Female'), (0.0, 'Families_with_female_householder__no_husband_present'), (0.0, 'Exempt_Legal_Accounting_Disbursement'), (0.0, 'English'), (0.0, 'Educational_services3'), (0.0, 'Debt_Owed_By_Committee'), (0.0, 'Debt_Owe_To_Committee'), (0.0, 'Danish'), (0.0, 'Construction2'), (0.0, 'College_or_graduate_school'), (0.0, 'Civilian_labor_force'), (0.0, 'Cand_Loan'), (0.0, 'Cand_Contribution'), (0.0, 'Average_household_size_of_owneroccupied_unit'), (0.0, 'Arts__entertainment__and_recreation3'), (0.0, 'Arts__entertainment__and_recreation2'), (0.0, 'Admin_and_support_and_waste_mngmt_and_remediation_services1'), (0.0, 'Accommodation_and_food_services3'), (0.0, '9th_to_12th_grade__no_diploma'), (0.0, '85_years_and_over'), (0.0, '600_to_799'), (0.0, '55_to_59_years'), (0.0, '3_000_or_more2'), (0.0, '35_000_to_49_999'), (0.0, '300_000_to_499_999'), (0.0, '25_000_to_34_999'), (0.0, '1_500_to_1_999a'), (0.0, '1_000_or_more'), (0.0, '1_000_000_or_more'), (0.0, '18_to_64_years'), (0.0, '15_000_to_24_999'), (0.0, '10_000_to_14_999')]

In [ ]:
#First try with data_retrieval_clean data
(0.06944683206013694, 'Native'),
 (0.06778545248736681, 'Housing_units_without_a_mortgage'),
 (0.050590582802684705, 'Public_transportation_excluding_taxicab'),
 (0.04663181036547453, 'Foreign_born'),
 (0.04019098000469825, 'Owneroccupied'),
 (0.0257764734000736, 'Less_than_50_000'),
 (0.02407910813952162, 'Mining__quarrying__and_oil_and_gas_extraction3'),
 (0.02358109813657187, '50_000_to_99_999'),
 (0.019383439610887194, '100_000_to_149_999a'),
 (0.01707200663316665, '250_to_399'),
 (0.016187125862931424, 'With_a_disability3'),
 (0.015597152867403583, 'Arab'),
 (0.012652051821809101, 'German'),
 (0.012108126027063525, 'Scottish'),
 (0.011848994143518959, 'Some_other_race'),
 (0.01182472992222696, 'Dutch'),
 (0.01158744209442443, 'Irish'),
 (0.011030210901114768, '150_000_to_199_999'),
 (0.010920211307753605, 'American'),

In [ ]:
# second run with data_retrieval_clean data
(0.06140897554225361, 'Public_transportation_excluding_taxicab'),
 (0.05564804927143511, '1_500_to_1_999b'),
 (0.04986879648029331, '500_to_999a'),
 (0.04641224812493576, 'Median_dollars4'),
 (0.04117606192269824, 'Native'),
 (0.02914198592070656, 'Civilian_veterans'),
 (0.02816764754041008, 'Foreign_born'),
 (0.02196962354847624, 'Utilities3'),
 (0.01932114240686124, 'White'),
 (0.017436264617090042, 'Less_than_250'),
 (0.016709011652123476, 'ScotchIrish'),
 (0.015632189495193835, 'Renteroccupied'),
 (0.014730613243925657, 'Median_dollars1'),
 (0.013009557972679917, 'Less_than_50_000'),
 (0.0128419682648537, 'State_of_residence'),
 (0.01178701469422252, 'Professional__scientific__and_technical_services2'),
 (0.011691944646157174, 'Mining__quarrying__and_oil_and_gas_extraction2'),
 (0.010354694193243235, '250_to_399'),
 (0.009837569380230409, 'Median_dollars3'),
 (0.009830284750372158, '3_000_or_more2'),

In [ ]:
# third run with data_retrieval_clean data
0.058985033306369936, 'Public_transportation_excluding_taxicab'),
 (0.05363083135079348, 'Foreign_born'),
 (0.0377943902953491, 'Born_in_United_States'),
 (0.03170276382718641, 'Less_than_250'),
 (0.02990366159470927, '400_to_599'),
 (0.022142544066125966, '500_to_999a'),
 (0.021766116909306528, 'Housing_units_without_a_mortgage'),
 (0.019541834681959046, 'American'),
 (0.017272436210601615, 'Agriculture__forestry__fishing_and_hunting2'),
 (0.016765124456656972, '1_000_to_1_499a'),
 (0.016476507614901503, '50_000_to_74_999'),
 (0.01635545048961632, '50_000_to_99_999'),
 (0.01624786684572141, 'Civilian_veterans'),
 (0.01455194320512294, 'Less_than_500a'),
 (0.014469412478834376, '2_500_to_2_999a'),
 (0.014147755160758302, 'Occupied_units_paying_rent'),
 (0.013577819313344324, 'Renteroccupied'),
 (0.012669475287774012, 'Dutch'),
 (0.012534509859784113, 'ScotchIrish'),

In [ ]:
# fourth run with data_retrieval_clean data
(0.05443605263554082,
  'Agriculture__forestry__fishing_and_hunting__and_mining'),
 (0.05331800911776474, 'Public_transportation_excluding_taxicab'),
 (0.043511165934758046, '100_000_to_149_999a'),
 (0.041478952411772005, '250_to_399'),
 (0.036209294104134176, 'American'),
 (0.03291548319024016, '50_000_to_99_999'),
 (0.03136532423900623, 'Born_in_United_States'),
 (0.024699234868376167, 'Irish'),
 (0.02316758927604264, 'Native'),
 (0.02094346655578025, '150_000_to_199_999'),
 (0.02068622130895132, 'Agriculture__forestry__fishing_and_hunting1'),
 (0.017511618212175336, 'Mining__quarrying__and_oil_and_gas_extraction3'),
 (0.015991304652452097, 'Graduate_or_professional_degree'),
 (0.015544767355850374, 'Housing_units_without_a_mortgage'),
 (0.015374821157004958, 'Less_than_500a'),
 (0.015315536150772505, '400_to_599'),
 (0.01489795815184081, 'Educational_services3'),
 (0.013236694535956273, '3_000_or_more2'),
 (0.013215176415903954, 'Owneroccupied'),

In [ ]:
# fith run with data_retrieval_clean data
(0.047907341751844315, '250_to_399'),
 (0.04515776937521011, '500_to_999a'),
 (0.04266156567569025, 'Housing_units_without_a_mortgage'),
 (0.037970116780786066, '1_500_to_1_999b'),
 (0.023685984307507173, 'Mining__quarrying__and_oil_and_gas_extraction1'),
 (0.022964961044644506, 'Public_transportation_excluding_taxicab'),
 (0.021056654970596368, 'Irish'),
 (0.019006866730144106, 'Less_than_50_000'),
 (0.018313353665120165, 'ScotchIrish'),
 (0.017954801373800035, 'Agriculture__forestry__fishing_and_hunting1'),
 (0.01686848019637896, 'Median_dollars2'),
 (0.016113214087596632, 'White'),
 (0.01605236057002089,
  'Agriculture__forestry__fishing_and_hunting__and_mining'),
 (0.015397615765094214, '2_500_to_2_999b'),
 (0.01532088523993141, 'Foreign_born'),
 (0.015138019672333403, '50_000_to_99_999'),
 (0.01499529732662214, 'Utilities3'),
 (0.014448613253307898, 'American'),