In [132]:
# Matthew Berning
# Dependencies
import numpy as np
import pandas as pd
import numpy
from numpy import array
from sqlalchemy import create_engine
import pymysql

In [133]:
election_dataset_raw = pd.read_csv('../database/data_retrieval_clean.csv')
election_dataset_raw.head()

,st_abbrev,district,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,...,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3,Industries_not_classified4,state_dist
0,AK,0,REP,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,...,193,1128,270,2633,569,2156,1823,40,0,AK_00
1,AL,1,REP,1325140,662806,1108650.0,0.0,264612.0,10105.0,274717.0,...,111,749,144,1427,198,1331,1663,21,0,AL_01
2,AL,2,REP,2506890,2100810,451536.0,0.0,741087.0,46129.8,787217.0,...,85,578,131,1538,159,1347,1673,29,0,AL_02
3,AL,3,REP,1219670,857764,887448.0,0.0,450890.0,9667.0,460557.0,...,47,521,89,1142,94,1186,1402,21,0,AL_03
4,AL,4,REP,1487010,853026,1099490.0,0.0,430365.0,23449.0,453814.0,...,76,401,58,1548,135,1060,1440,30,0,AL_04

In [134]:
election_dataset = election_dataset_raw.drop(['id','st_abbrev', 'district', "Industries_not_classified4", "state_dist"], axis=1)

In [135]:
election_dataset.head()

,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,Other_Committee_Contribution,Party_Committee_Contribution,...,Real_estate_and_rental_and_leasing3,Professional__scientific__and_technical_services3,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3
0,REP,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,481912.0,0.00,...,933,1960,193,1128,270,2633,569,2156,1823,40
1,REP,1325140,662806,1108650.0,0.0,264612.0,10105.0,274717.0,985650.0,663.98,...,846,1420,111,749,144,1427,198,1331,1663,21
2,REP,2506890,2100810,451536.0,0.0,741087.0,46129.8,787217.0,1628590.0,5000.00,...,561,1249,85,578,131,1538,159,1347,1673,29
3,REP,1219670,857764,887448.0,0.0,450890.0,9667.0,460557.0,742720.0,11500.00,...,462,853,47,521,89,1142,94,1186,1402,21
4,REP,1487010,853026,1099490.0,0.0,430365.0,23449.0,453814.0,1020840.0,0.00,...,385,808,76,401,58,1548,135,1060,1440,30

In [136]:
X = election_dataset.drop("party", axis=1)
y = election_dataset["party"]
print(X.shape, y.shape)

(434, 323) (434,)

In [137]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [138]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=500, activation='relu', input_dim=323))
model.add(Dense(units=500, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [139]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=20,
    shuffle=True,
    verbose=2
)

Epoch 1/20
 - 0s - loss: 0.4424 - acc: 0.8000
Epoch 2/20
 - 0s - loss: 0.1563 - acc: 0.9385
Epoch 3/20
 - 0s - loss: 0.0700 - acc: 0.9754
Epoch 4/20
 - 0s - loss: 0.0538 - acc: 0.9877
Epoch 5/20
 - 0s - loss: 0.0394 - acc: 0.9908
Epoch 6/20
 - 0s - loss: 0.0241 - acc: 0.9908
Epoch 7/20
 - 0s - loss: 0.0086 - acc: 1.0000
Epoch 8/20
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 9/20
 - 0s - loss: 0.0033 - acc: 1.0000
Epoch 10/20
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 11/20
 - 0s - loss: 0.0017 - acc: 1.0000
Epoch 12/20
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 13/20
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 14/20
 - 0s - loss: 9.2526e-04 - acc: 1.0000
Epoch 15/20
 - 0s - loss: 8.1077e-04 - acc: 1.0000
Epoch 16/20
 - 0s - loss: 7.1399e-04 - acc: 1.0000
Epoch 17/20
 - 0s - loss: 6.3221e-04 - acc: 1.0000
Epoch 18/20
 - 0s - loss: 5.7709e-04 - acc: 1.0000
Epoch 19/20
 - 0s - loss: 5.1919e-04 - acc: 1.0000
Epoch 20/20
 - 0s - loss: 4.7565e-04 - acc: 1.0000

In [111]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 0.8927089101677641, Accuracy: 0.8440366988882012

In [112]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\OI\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [113]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels    : {list(y_test[:10])}")

Predicted classes: ['DEM' 'DEM' 'DEM' 'REP' 'DEM' 'DEM' 'DEM' 'REP' 'DEM' 'DEM']
Actual Labels    : ['REP', 'REP', 'DEM', 'REP', 'DEM', 'DEM', 'DEM', 'REP', 'DEM', 'DEM']

In [114]:
election_dataset_minus_label = election_dataset.drop(['party'], axis=1)
election_dataset_minus_label.head(1)

,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,Other_Committee_Contribution,Party_Committee_Contribution,Cand_Contribution,...,Real_estate_and_rental_and_leasing3,Professional__scientific__and_technical_services3,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3
0,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,481912.0,0.0,0.0,...,933,1960,193,1128,270,2633,569,2156,1823,40

In [115]:
all_values_list = election_dataset_minus_label.values.tolist()
all_values_scaled = X_scaler.transform(all_values_list)
all_values_a = np.array(all_values_scaled)

In [116]:
all_values_probabilities = model.predict(all_values_scaled, verbose=0)
all_values_probabilities

array([[9.72043633e-01, 2.79563814e-02],
       [2.57226638e-05, 9.99974251e-01],
       [1.02298782e-06, 9.99998927e-01],
       [1.50724381e-05, 9.99984980e-01],
       [3.04409491e-06, 9.99996901e-01],
       [4.88839287e-05, 9.99951124e-01],
       [1.59486859e-07, 9.99999881e-01],
       [9.99985337e-01, 1.46863104e-05],
       [3.70360294e-06, 9.99996305e-01],
       [1.49122532e-03, 9.98508751e-01],
       [1.00389486e-02, 9.89961028e-01],
       [3.56340206e-05, 9.99964356e-01],
       [7.81331062e-01, 2.18668967e-01],
       [9.97510195e-01, 2.48983176e-03],
       [9.99944925e-01, 5.50610675e-05],
       [5.07010878e-10, 1.00000000e+00],
       [3.23891709e-06, 9.99996781e-01],
       [4.73680033e-04, 9.99526381e-01],
       [1.00000000e+00, 2.07908446e-08],
       [2.20135684e-04, 9.99779880e-01],
       [9.99998212e-01, 1.78722746e-06],
       [1.48994441e-03, 9.98510063e-01],
       [9.99996781e-01, 3.19178730e-06],
       [9.99783218e-01, 2.16740882e-04],
       [1.00000000e+00, 2.56370006e-16],
       [1.00000000e+00, 2.34035546e-09],
       [1.00000000e+00, 8.05336631e-11],
       [9.99999642e-01, 3.18047938e-07],
       [9.99998808e-01, 1.15141290e-06],
       [1.00000000e+00, 6.18317723e-12],
       [1.00000000e+00, 1.48899296e-11],
       [9.99998569e-01, 1.42472447e-06],
       [9.99124110e-01, 8.75872385e-04],
       [9.99971032e-01, 2.90229873e-05],
       [9.99984145e-01, 1.59047977e-05],
       [1.00000000e+00, 3.02232176e-12],
       [1.23906575e-05, 9.99987602e-01],
       [9.99997497e-01, 2.53011012e-06],
       [9.99999404e-01, 5.49625440e-07],
       [9.99800622e-01, 1.99373710e-04],
       [1.00000000e+00, 2.19435563e-08],
       [1.00000000e+00, 2.51508494e-14],
       [9.99999642e-01, 3.40283293e-07],
       [9.74255323e-01, 2.57447381e-02],
       [1.00000000e+00, 2.56443027e-11],
       [9.99998808e-01, 1.14384261e-06],
       [9.99988556e-01, 1.13975902e-05],
       [1.00000000e+00, 1.11178583e-13],
       [9.99999523e-01, 4.43949773e-07],
       [9.99999642e-01, 3.33449037e-07],
       [9.99455631e-01, 5.44323528e-04],
       [1.00000000e+00, 1.52338653e-09],
       [9.99833107e-01, 1.66839265e-04],
       [9.99599755e-01, 4.00278979e-04],
       [3.67275148e-04, 9.99632716e-01],
       [1.00000000e+00, 1.07126397e-09],
       [9.99998808e-01, 1.21084338e-06],
       [2.11914852e-02, 9.78808463e-01],
       [9.99999046e-01, 9.68856057e-07],
       [1.00000000e+00, 1.08285914e-08],
       [1.00000000e+00, 1.96698685e-10],
       [9.96521831e-01, 3.47814453e-03],
       [9.99993443e-01, 6.52736435e-06],
       [9.99955058e-01, 4.48855899e-05],
       [1.00000000e+00, 4.83880385e-08],
       [9.99958158e-01, 4.18109012e-05],
       [2.73216702e-03, 9.97267842e-01],
       [1.00000000e+00, 2.18820748e-08],
       [1.00000000e+00, 9.26156152e-10],
       [1.00000000e+00, 1.05925260e-08],
       [9.99996543e-01, 3.43715192e-06],
       [9.99836683e-01, 1.63335702e-04],
       [4.92063254e-01, 5.07936776e-01],
       [9.99434531e-01, 5.65398484e-04],
       [9.99999881e-01, 1.64469341e-07],
       [9.99999404e-01, 6.23392509e-07],
       [3.13456949e-05, 9.99968648e-01],
       [3.41808569e-04, 9.99658227e-01],
       [7.62063265e-01, 2.37936705e-01],
       [9.99999404e-01, 5.85034741e-07],
       [9.99255121e-01, 7.44863588e-04],
       [9.99975681e-01, 2.42598580e-05],
       [9.95715559e-01, 4.28441074e-03],
       [9.99935269e-01, 6.46860135e-05],
       [9.99999285e-01, 6.93531831e-07],
       [9.99963522e-01, 3.64579137e-05],
       [6.19948059e-02, 9.38005209e-01],
       [2.48242832e-05, 9.99975204e-01],
       [9.99826729e-01, 1.73333799e-04],
       [1.88541739e-12, 1.00000000e+00],
       [3.22368760e-06, 9.99996781e-01],
       [8.28223288e-01, 1.71776757e-01],
       [9.99920130e-01, 7.98515975e-05],
       [1.84852979e-03, 9.98151481e-01],
       [5.26140582e-07, 9.99999523e-01],
       [3.30696942e-10, 1.00000000e+00],
       [3.17076221e-03, 9.96829212e-01],
       [2.00263617e-06, 9.99997973e-01],
       [2.79108178e-07, 9.99999762e-01],
       [9.99998927e-01, 1.12877126e-06],
       [9.99153614e-01, 8.46397947e-04],
       [9.99838471e-01, 1.61559670e-04],
       [9.94851649e-01, 5.14837634e-03],
       [9.99999881e-01, 1.20451077e-07],
       [7.28778599e-04, 9.99271214e-01],
       [9.99759018e-01, 2.40964990e-04],
       [9.99974251e-01, 2.58007403e-05],
       [1.51418441e-03, 9.98485863e-01],
       [1.57201465e-03, 9.98427987e-01],
       [9.99536514e-01, 4.63542296e-04],
       [1.77328232e-07, 9.99999881e-01],
       [9.99780118e-01, 2.19942696e-04],
       [1.22295796e-05, 9.99987721e-01],
       [9.99943495e-01, 5.65087612e-05],
       [5.57858031e-04, 9.99442160e-01],
       [5.61080515e-06, 9.99994397e-01],
       [4.56919988e-05, 9.99954343e-01],
       [7.07719028e-02, 9.29228067e-01],
       [9.99182761e-01, 8.17236374e-04],
       [5.25270980e-06, 9.99994755e-01],
       [9.98737633e-01, 1.26241124e-03],
       [1.96455017e-06, 9.99998093e-01],
       [9.99888539e-01, 1.11436100e-04],
       [9.99999881e-01, 9.12844058e-08],
       [9.99797523e-01, 2.02436306e-04],
       [3.57624638e-04, 9.99642372e-01],
       [3.19103186e-04, 9.99680877e-01],
       [1.39512110e-07, 9.99999881e-01],
       [1.00000000e+00, 3.73890217e-08],
       [9.99998569e-01, 1.39504277e-06],
       [9.94346440e-01, 5.65351406e-03],
       [9.94448900e-01, 5.55113843e-03],
       [9.99660969e-01, 3.39041493e-04],
       [5.30775011e-01, 4.69224960e-01],
       [2.09951713e-06, 9.99997854e-01],
       [3.32332973e-04, 9.99667645e-01],
       [9.99999642e-01, 3.00158945e-07],
       [9.99993920e-01, 6.11325004e-06],
       [9.99984145e-01, 1.58679832e-05],
       [3.51118296e-03, 9.96488810e-01],
       [1.88300665e-03, 9.98116970e-01],
       [9.99728262e-01, 2.71721627e-04],
       [7.99714689e-06, 9.99992013e-01],
       [2.21374575e-02, 9.77862597e-01],
       [9.98765230e-01, 1.23483734e-03],
       [6.34716343e-05, 9.99936581e-01],
       [9.99999881e-01, 1.71256900e-07],
       [9.99782622e-01, 2.17371911e-04],
       [9.99999523e-01, 4.97613826e-07],
       [9.99999881e-01, 8.03066129e-08],
       [9.99999523e-01, 4.51614909e-07],
       [9.99999523e-01, 5.32231923e-07],
       [9.99998212e-01, 1.74233526e-06],
       [9.99995351e-01, 4.59820558e-06],
       [9.97743130e-01, 2.25684419e-03],
       [6.96341740e-05, 9.99930382e-01],
       [5.20717276e-06, 9.99994755e-01],
       [6.30656405e-06, 9.99993682e-01],
       [7.14666967e-05, 9.99928474e-01],
       [8.00434136e-05, 9.99919891e-01],
       [9.99336541e-01, 6.63381768e-04],
       [5.56239638e-06, 9.99994397e-01],
       [3.04357536e-06, 9.99996901e-01],
       [8.87858841e-05, 9.99911189e-01],
       [2.80819004e-05, 9.99971867e-01],
       [9.99597251e-01, 4.02708218e-04],
       [3.73369490e-04, 9.99626637e-01],
       [4.57878031e-07, 9.99999523e-01],
       [1.93499295e-06, 9.99998093e-01],
       [4.81558368e-02, 9.51844156e-01],
       [2.83413382e-08, 1.00000000e+00],
       [2.88406591e-06, 9.99997139e-01],
       [3.45175317e-03, 9.96548235e-01],
       [9.99988437e-01, 1.16167557e-05],
       [9.99095798e-01, 9.04264103e-04],
       [4.18160853e-05, 9.99958158e-01],
       [4.67183272e-04, 9.99532819e-01],
       [5.65642949e-05, 9.99943376e-01],
       [2.62889826e-05, 9.99973655e-01],
       [9.99992967e-01, 7.07856225e-06],
       [9.99999523e-01, 4.71071075e-07],
       [9.99998450e-01, 1.59526553e-06],
       [1.00000000e+00, 5.67339925e-11],
       [1.00000000e+00, 7.05026038e-10],
       [1.00000000e+00, 3.12216493e-08],
       [1.00000000e+00, 3.54051369e-13],
       [1.00000000e+00, 3.82630532e-08],
       [9.99984741e-01, 1.52956800e-05],
       [2.05698074e-03, 9.97942984e-01],
       [9.99909759e-01, 9.02464744e-05],
       [9.99999881e-01, 1.52857311e-07],
       [9.99999642e-01, 3.03116110e-07],
       [9.99644756e-01, 3.55188764e-04],
       [1.00000000e+00, 3.90152657e-08],
       [9.99995947e-01, 4.04812181e-06],
       [1.00000000e+00, 1.44390508e-08],
       [9.99915719e-01, 8.42628651e-05],
       [9.99588907e-01, 4.11115761e-04],
       [2.33671046e-04, 9.99766290e-01],
       [1.21254325e-05, 9.99987841e-01],
       [9.98344421e-01, 1.65556406e-03],
       [9.99942183e-01, 5.77565843e-05],
       [1.00000000e+00, 4.22118607e-09],
       [9.99999166e-01, 7.87802151e-07],
       [1.74480272e-04, 9.99825537e-01],
       [6.66873180e-04, 9.99333084e-01],
       [1.13787364e-05, 9.99988675e-01],
       [9.99772489e-01, 2.27495373e-04],
       [5.49696815e-05, 9.99945045e-01],
       [2.42141482e-06, 9.99997616e-01],
       [9.99988317e-01, 1.16785486e-05],
       [9.98036921e-01, 1.96314743e-03],
       [4.34171828e-03, 9.95658278e-01],
       [9.84186113e-01, 1.58138927e-02],
       [9.99997735e-01, 2.24465157e-06],
       [9.98591840e-01, 1.40812388e-03],
       [9.99998450e-01, 1.60436480e-06],
       [5.91396005e-04, 9.99408603e-01],
       [9.95642781e-01, 4.35718475e-03],
       [2.28055507e-01, 7.71944463e-01],
       [9.99875784e-01, 1.24192084e-04],
       [9.71118748e-01, 2.88813245e-02],
       [1.33863864e-06, 9.99998689e-01],
       [3.92222773e-06, 9.99996066e-01],
       [8.13982725e-01, 1.86017290e-01],
       [2.61611899e-06, 9.99997377e-01],
       [5.09052188e-05, 9.99949098e-01],
       [3.50587186e-07, 9.99999642e-01],
       [6.48389323e-05, 9.99935150e-01],
       [9.99873161e-01, 1.26796876e-04],
       [7.09056076e-06, 9.99992967e-01],
       [3.86129841e-06, 9.99996185e-01],
       [7.16015165e-07, 9.99999285e-01],
       [9.99567688e-01, 4.32271976e-04],
       [1.51223539e-05, 9.99984860e-01],
       [1.89359000e-07, 9.99999762e-01],
       [9.99693394e-01, 3.06596281e-04],
       [1.41411764e-03, 9.98585939e-01],
       [3.85493308e-07, 9.99999642e-01],
       [1.22180878e-04, 9.99877810e-01],
       [9.99999285e-01, 7.07536344e-07],
       [1.75402977e-03, 9.98245955e-01],
       [3.01271320e-05, 9.99969840e-01],
       [9.14629491e-05, 9.99908566e-01],
       [3.81893216e-04, 9.99618053e-01],
       [8.48635740e-04, 9.99151349e-01],
       [4.32579924e-04, 9.99567449e-01],
       [5.08419507e-05, 9.99949098e-01],
       [1.38110609e-03, 9.98618841e-01],
       [9.99985218e-01, 1.47293840e-05],
       [9.99998808e-01, 1.13695501e-06],
       [9.82116401e-01, 1.78835783e-02],
       [1.00000000e+00, 1.21248966e-09],
       [1.00000000e+00, 1.82229006e-11],
       [9.99442518e-01, 5.57500054e-04],
       [9.97740507e-01, 2.25954852e-03],
       [9.99980688e-01, 1.93023261e-05],
       [1.64449797e-03, 9.98355448e-01],
       [1.00000000e+00, 2.03655381e-09],
       [9.99963880e-01, 3.60762970e-05],
       [1.00000000e+00, 5.08728846e-08],
       [1.00000000e+00, 6.79893741e-09],
       [9.99970913e-01, 2.90744556e-05],
       [9.98984158e-01, 1.01583754e-03],
       [9.98337746e-01, 1.66222441e-03],
       [9.99993205e-01, 6.78157949e-06],
       [9.99999642e-01, 3.36258267e-07],
       [1.41336629e-03, 9.98586655e-01],
       [9.99918699e-01, 8.13534498e-05],
       [4.86337304e-01, 5.13662696e-01],
       [9.99997854e-01, 2.12332588e-06],
       [9.99999881e-01, 6.08110753e-08],
       [9.99966860e-01, 3.31299816e-05],
       [1.00000000e+00, 3.69346090e-12],
       [1.00000000e+00, 3.89630921e-14],
       [1.00000000e+00, 3.19414339e-09],
       [1.00000000e+00, 9.27609226e-14],
       [9.99999523e-01, 4.92753031e-07],
       [9.99707282e-01, 2.92731071e-04],
       [9.99818742e-01, 1.81282187e-04],
       [9.99998927e-01, 1.06960965e-06],
       [9.99997020e-01, 2.99670364e-06],
       [9.99816835e-01, 1.83176104e-04],
       [4.97213739e-04, 9.99502778e-01],
       [9.94678497e-01, 5.32151526e-03],
       [4.58172988e-03, 9.95418310e-01],
       [3.45278205e-03, 9.96547282e-01],
       [9.94533181e-01, 5.46680298e-03],
       [9.99437153e-01, 5.62824716e-04],
       [1.61942618e-04, 9.99837995e-01],
       [9.99999523e-01, 4.75273112e-07],
       [9.99996781e-01, 3.22878577e-06],
       [1.00000000e+00, 1.44686592e-08],
       [9.99999881e-01, 1.28858161e-07],
       [9.99996662e-01, 3.38240898e-06],
       [1.00000000e+00, 4.14883433e-10],
       [1.00000000e+00, 1.98296735e-09],
       [2.67231581e-03, 9.97327685e-01],
       [3.63338436e-03, 9.96366620e-01],
       [9.99990463e-01, 9.52614846e-06],
       [2.09602498e-04, 9.99790370e-01],
       [9.98912454e-01, 1.08751946e-03],
       [1.95196539e-03, 9.98048067e-01],
       [4.67175050e-05, 9.99953270e-01],
       [1.67227443e-02, 9.83277321e-01],
       [3.65570304e-05, 9.99963403e-01],
       [9.99973416e-01, 2.65378239e-05],
       [2.12280895e-04, 9.99787748e-01],
       [3.01186403e-04, 9.99698877e-01],
       [1.49794241e-05, 9.99984980e-01],
       [3.12080992e-05, 9.99968767e-01],
       [5.86193607e-07, 9.99999404e-01],
       [9.99885559e-01, 1.14410039e-04],
       [5.64235670e-04, 9.99435723e-01],
       [4.22702084e-04, 9.99577343e-01],
       [2.50648782e-06, 9.99997497e-01],
       [1.40414500e-04, 9.99859571e-01],
       [9.96607542e-01, 3.39250034e-03],
       [9.99997497e-01, 2.46851346e-06],
       [5.55821054e-04, 9.99444187e-01],
       [9.99999881e-01, 7.43958140e-08],
       [9.99777377e-01, 2.22582021e-04],
       [9.97732520e-01, 2.26739631e-03],
       [2.62789428e-04, 9.99737203e-01],
       [1.51936067e-04, 9.99848008e-01],
       [6.69031229e-04, 9.99330997e-01],
       [9.41086411e-01, 5.89136034e-02],
       [2.73434934e-03, 9.97265697e-01],
       [4.36857482e-03, 9.95631456e-01],
       [2.66776374e-03, 9.97332215e-01],
       [6.89606299e-04, 9.99310374e-01],
       [1.00000000e+00, 1.80635702e-08],
       [9.97345865e-01, 2.65419041e-03],
       [9.99999523e-01, 4.37740226e-07],
       [9.91574705e-01, 8.42532609e-03],
       [3.44379951e-05, 9.99965549e-01],
       [9.93507504e-01, 6.49246946e-03],
       [9.99851227e-01, 1.48802443e-04],
       [9.93929029e-01, 6.07094122e-03],
       [9.99112308e-01, 8.87624687e-04],
       [5.34605933e-03, 9.94653940e-01],
       [9.99999762e-01, 2.65590046e-07],
       [9.99987841e-01, 1.21554076e-05],
       [9.96364892e-01, 3.63513525e-03],
       [2.95428981e-06, 9.99997020e-01],
       [1.62086835e-05, 9.99983788e-01],
       [9.92409213e-08, 9.99999881e-01],
       [2.85526198e-06, 9.99997139e-01],
       [9.99916434e-01, 8.35479659e-05],
       [1.06050073e-04, 9.99893904e-01],
       [1.99023215e-03, 9.98009741e-01],
       [7.20855837e-08, 9.99999881e-01],
       [2.17481338e-05, 9.99978304e-01],
       [5.42618636e-06, 9.99994516e-01],
       [4.70702889e-06, 9.99995351e-01],
       [7.63526652e-03, 9.92364764e-01],
       [1.67533749e-14, 1.00000000e+00],
       [5.25136434e-10, 1.00000000e+00],
       [3.94488188e-06, 9.99996066e-01],
       [9.99998689e-01, 1.32300636e-06],
       [7.73241425e-07, 9.99999285e-01],
       [5.62130567e-03, 9.94378746e-01],
       [3.90214791e-06, 9.99996066e-01],
       [1.58515256e-02, 9.84148502e-01],
       [1.50675565e-04, 9.99849319e-01],
       [4.82676041e-05, 9.99951720e-01],
       [9.97654021e-01, 2.34602112e-03],
       [9.99928117e-01, 7.19033851e-05],
       [5.19982934e-01, 4.80017066e-01],
       [9.99983788e-01, 1.62357719e-05],
       [2.93346558e-04, 9.99706686e-01],
       [1.08306913e-03, 9.98916984e-01],
       [9.99751627e-01, 2.48419266e-04],
       [9.95618522e-01, 4.38139355e-03],
       [1.00800826e-03, 9.98992026e-01],
       [7.88904261e-04, 9.99211073e-01],
       [8.86050522e-01, 1.13949515e-01],
       [1.85936540e-06, 9.99998093e-01],
       [3.35501391e-04, 9.99664545e-01],
       [6.35137083e-04, 9.99364913e-01],
       [9.99108374e-01, 8.91640200e-04],
       [9.99994993e-01, 4.96880557e-06],
       [3.96600711e-07, 9.99999642e-01],
       [9.99990344e-01, 9.69042139e-06],
       [1.38461660e-03, 9.98615384e-01],
       [9.99998093e-01, 1.88139779e-06],
       [9.99997735e-01, 2.21922005e-06],
       [9.98166382e-01, 1.83359301e-03],
       [1.00000000e+00, 4.15607744e-08],
       [1.39347303e-05, 9.99986053e-01],
       [1.63290004e-09, 1.00000000e+00],
       [9.47667559e-06, 9.99990582e-01],
       [1.64951532e-04, 9.99835014e-01],
       [9.99947429e-01, 5.25867908e-05],
       [5.99137273e-09, 1.00000000e+00],
       [9.99999404e-01, 6.05646392e-07],
       [1.38387977e-05, 9.99986172e-01],
       [3.29815739e-05, 9.99966979e-01],
       [1.97505746e-02, 9.80249405e-01],
       [9.99608576e-01, 3.91457346e-04],
       [1.13361236e-02, 9.88663852e-01],
       [1.00000000e+00, 3.45108688e-08],
       [1.00000000e+00, 4.04049121e-11],
       [9.99681473e-01, 3.18502891e-04],
       [9.99925375e-01, 7.45786965e-05],
       [9.98040378e-01, 1.95967685e-03],
       [3.80318816e-05, 9.99961972e-01],
       [1.07610389e-03, 9.98923838e-01],
       [9.99765217e-01, 2.34759471e-04],
       [1.00000000e+00, 6.23404702e-13],
       [1.65832012e-06, 9.99998331e-01],
       [9.99807656e-01, 1.92377134e-04],
       [9.99968052e-01, 3.19639112e-05],
       [9.99247074e-01, 7.52985768e-04],
       [9.99771655e-01, 2.28396253e-04],
       [1.22309162e-03, 9.98776853e-01],
       [2.32630031e-04, 9.99767363e-01],
       [4.35909315e-04, 9.99564111e-01],
       [9.99618173e-01, 3.81741440e-04],
       [1.00000000e+00, 1.53130140e-13],
       [9.99999523e-01, 4.81002076e-07],
       [9.99999404e-01, 5.40709664e-07],
       [1.63485785e-03, 9.98365104e-01],
       [9.99859214e-01, 1.40710690e-04],
       [9.95468020e-01, 4.53193672e-03],
       [9.99977231e-01, 2.27208802e-05],
       [8.71758908e-04, 9.99128282e-01],
       [6.44248867e-05, 9.99935627e-01],
       [4.39787610e-03, 9.95602131e-01],
       [9.85816121e-04, 9.99014139e-01],
       [4.02224105e-05, 9.99959826e-01],
       [1.05851548e-04, 9.99894142e-01],
       [1.98041489e-05, 9.99980211e-01],
       [1.96920541e-06, 9.99997973e-01]], dtype=float32)

In [117]:
model.predict_classes(all_values_scaled, verbose=1)

434/434 [==============================] - 0s 60us/step

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [118]:
all_values_classes = model.predict_classes(all_values_scaled, verbose=1)

434/434 [==============================] - 0s 46us/step

In [119]:
all_values_labels = label_encoder.inverse_transform(all_values_classes)

C:\Users\OI\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [120]:
all_values_labels_df = pd.DataFrame(all_values_labels)
all_values_labels_df = all_values_labels_df.rename(columns={0:"Predicted_Party"})
all_values_labels_df.head()

  Predicted Party
0             DEM
1             REP
2             REP
3             REP
4             REP

In [121]:
all_values_probabilities_df = pd.DataFrame(all_values_probabilities)
all_values_probabilities_df = all_values_probabilities_df.rename(columns={0:"Probability_of_DEM", 1:"Probability_of_REP"})
all_values_probabilities_df.head()

   Probability of DEM  Probability of REP
0            0.972044            0.027956
1            0.000026            0.999974
2            0.000001            0.999999
3            0.000015            0.999985
4            0.000003            0.999997

In [122]:
to_be_added = election_dataset_raw[["party", "state_dist"]]
to_be_added.head()

  party state_dist
0   REP      AK_00
1   REP      AL_01
2   REP      AL_02
3   REP      AL_03
4   REP      AL_04

In [126]:
output_df_concat = pd.concat([all_values_labels_df, all_values_probabilities_df, to_be_added], axis=1)

output_df = output_df_concat.rename(columns={"party":"Actual_Winning_Party"})

output_df.head()

,Predicted Party,Probability of DEM,Probability of REP,Actual Winning Party,state_dist
0,DEM,0.972044,0.027956,REP,AK_00
1,REP,0.000026,0.999974,REP,AL_01
2,REP,0.000001,0.999999,REP,AL_02
3,REP,0.000015,0.999985,REP,AL_03
4,REP,0.000003,0.999997,REP,AL_04

In [127]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 500)               162000
_________________________________________________________________
dense_8 (Dense)              (None, 500)               250500
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 1002
=================================================================
Total params: 413,502
Trainable params: 413,502
Non-trainable params: 0
_________________________________________________________________

In [128]:
# Establish Connection to MySQL
import pymysql
pymysql.install_as_MySQLdb()
engine = create_engine("mysql://root:$M$CK@butt.com@localhost:3306/election_prediction_db")
conn = engine.connect()

In [129]:
#check for tables
engine.table_names()

['candidate_finance',
 'district_demographic',
 'fips',
 'house_candidate',
 'us_congress',
 'us_congress_member',
 'us_congressional_district']

In [130]:
#push data into MySQL database
output_df.to_sql(name='neural_net_raw_output', con=engine, if_exists='append', index=False)

In [131]:
#confirm read into MySQL
pd.read_sql_query('select * from neural_net_raw_output', con=engine).head()

,Predicted Party,Probability of DEM,Probability of REP,Actual Winning Party,state_dist
0,DEM,0.972044,0.027956,REP,AK_00
1,REP,0.000026,0.999974,REP,AL_01
2,REP,0.000001,0.999999,REP,AL_02
3,REP,0.000015,0.999985,REP,AL_03
4,REP,0.000003,0.999997,REP,AL_04