In [1]:
# Matthew Berning
# Dependencies
import numpy as np
import pandas as pd
import numpy
from numpy import array
from sqlalchemy import create_engine
import pymysql

In [2]:
election_dataset_raw = pd.read_csv('../database/data_retrieval_clean.csv')
election_dataset_raw.head()

,st_abbrev,district,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,...,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3,Industries_not_classified4,state_dist
0,AK,0,REP,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,...,193,1128,270,2633,569,2156,1823,40,0,AK_00
1,AL,1,REP,1325140,662806,1108650.0,0.0,264612.0,10105.0,274717.0,...,111,749,144,1427,198,1331,1663,21,0,AL_01
2,AL,2,REP,2506890,2100810,451536.0,0.0,741087.0,46129.8,787217.0,...,85,578,131,1538,159,1347,1673,29,0,AL_02
3,AL,3,REP,1219670,857764,887448.0,0.0,450890.0,9667.0,460557.0,...,47,521,89,1142,94,1186,1402,21,0,AL_03
4,AL,4,REP,1487010,853026,1099490.0,0.0,430365.0,23449.0,453814.0,...,76,401,58,1548,135,1060,1440,30,0,AL_04

In [3]:
election_dataset = election_dataset_raw.drop(['id','st_abbrev', 'district', "Industries_not_classified4", "state_dist"], axis=1)

In [5]:
election_dataset_restricted = election_dataset[["party","Agriculture__forestry__fishing_and_hunting__and_mining", "100_000_to_149_999a", "American", "Less_than_50_000", "Public_transportation_excluding_taxicab", "ScotchIrish", "50_000_to_99_999", "Civilian_veterans", "Mining__quarrying__and_oil_and_gas_extraction2", "Unemployed", "White", "1_500_to_1_999b", "250_to_399", "500_to_999a", "Born_in_United_States", "Foreign_born", "Housing_units_without_a_mortgage", "Irish", "Median_dollars4", "Owneroccupied", "Asian", "Less_than_250", "Mining__quarrying__and_oil_and_gas_extraction3", "Native", "50_000_to_74_999", "Arab", "English", "Median_dollars2", "Median_dollars3", "Mining__quarrying__and_oil_and_gas_extraction1", "Scottish", "Prof__scientific__and_mngmnt__and_admin_and_waste_mngmnt_ser", "150_000_to_199_999", "400_to_599", "Abroad", "Born_in_PR__US_Is_areas_or_abroad_to_US_parents", "Graduate_or_professional_degree", "Median_dollars1", "Moved_in_2000_to_2009", "Occupied_units_paying_rent", "Same_state", "Some_other_race"]]

election_dataset_restricted.head()

,party,Agriculture__forestry__fishing_and_hunting__and_mining,100_000_to_149_999a,American,Less_than_50_000,Public_transportation_excluding_taxicab,ScotchIrish,50_000_to_99_999,Civilian_veterans,Mining__quarrying__and_oil_and_gas_extraction2,...,150_000_to_199_999,400_to_599,Abroad,Born_in_PR__US_Is_areas_or_abroad_to_US_parents,Graduate_or_professional_degree,Median_dollars1,Moved_in_2000_to_2009,Occupied_units_paying_rent,Same_state,Some_other_race
0,REP,15248,10374,21878,11347,5827,10665,6983,64057,1447939,...,18203,13275,6703,19529,52240,273100,62825,84396,16924,11279
1,REP,4133,39246,104645,19009,954,12754,33724,50054,35353,...,32011,20199,1165,6054,42131,147100,59609,72590,9558,7077
2,REP,6352,30956,129642,22898,144,8171,36236,59097,10021,...,25722,15553,3693,7855,39425,131400,60973,77234,24075,5410
3,REP,3750,34977,120734,33006,447,9736,41901,51339,32435,...,27937,20357,830,6847,43148,127600,61221,73773,25236,8383
4,REP,5901,31552,177643,33194,634,7337,47038,40343,121149,...,28195,19551,1507,4336,33426,117700,61210,58061,20178,16865

In [11]:
X = election_dataset_restricted.drop("party", axis=1)
y = election_dataset_restricted["party"]
print(X.shape, y.shape)

(434, 42) (434,)

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [13]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=80, activation='relu', input_dim=42))
model.add(Dense(units=80, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [14]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=43,
    shuffle=True,
    verbose=2
)

Epoch 1/43
 - 0s - loss: 0.5732 - acc: 0.6677
Epoch 2/43
 - 0s - loss: 0.4077 - acc: 0.8246
Epoch 3/43
 - 0s - loss: 0.3729 - acc: 0.8338
Epoch 4/43
 - 0s - loss: 0.3478 - acc: 0.8431
Epoch 5/43
 - 0s - loss: 0.3251 - acc: 0.8523
Epoch 6/43
 - 0s - loss: 0.3070 - acc: 0.8615
Epoch 7/43
 - 0s - loss: 0.2920 - acc: 0.8677
Epoch 8/43
 - 0s - loss: 0.2785 - acc: 0.8769
Epoch 9/43
 - 0s - loss: 0.2638 - acc: 0.8923
Epoch 10/43
 - 0s - loss: 0.2559 - acc: 0.8923
Epoch 11/43
 - 0s - loss: 0.2432 - acc: 0.9108
Epoch 12/43
 - 0s - loss: 0.2319 - acc: 0.9200
Epoch 13/43
 - 0s - loss: 0.2206 - acc: 0.9262
Epoch 14/43
 - 0s - loss: 0.2121 - acc: 0.9200
Epoch 15/43
 - 0s - loss: 0.2051 - acc: 0.9262
Epoch 16/43
 - 0s - loss: 0.1968 - acc: 0.9323
Epoch 17/43
 - 0s - loss: 0.1907 - acc: 0.9385
Epoch 18/43
 - 0s - loss: 0.1802 - acc: 0.9354
Epoch 19/43
 - 0s - loss: 0.1731 - acc: 0.9385
Epoch 20/43
 - 0s - loss: 0.1643 - acc: 0.9385
Epoch 21/43
 - 0s - loss: 0.1533 - acc: 0.9415
Epoch 22/43
 - 0s - loss: 0.1506 - acc: 0.9446
Epoch 23/43
 - 0s - loss: 0.1461 - acc: 0.9538
Epoch 24/43
 - 0s - loss: 0.1348 - acc: 0.9631
Epoch 25/43
 - 0s - loss: 0.1296 - acc: 0.9538
Epoch 26/43
 - 0s - loss: 0.1221 - acc: 0.9569
Epoch 27/43
 - 0s - loss: 0.1228 - acc: 0.9538
Epoch 28/43
 - 0s - loss: 0.1239 - acc: 0.9662
Epoch 29/43
 - 0s - loss: 0.1107 - acc: 0.9538
Epoch 30/43
 - 0s - loss: 0.1030 - acc: 0.9723
Epoch 31/43
 - 0s - loss: 0.0974 - acc: 0.9723
Epoch 32/43
 - 0s - loss: 0.0909 - acc: 0.9723
Epoch 33/43
 - 0s - loss: 0.0805 - acc: 0.9846
Epoch 34/43
 - 0s - loss: 0.0764 - acc: 0.9877
Epoch 35/43
 - 0s - loss: 0.0735 - acc: 0.9815
Epoch 36/43
 - 0s - loss: 0.0679 - acc: 0.9877
Epoch 37/43
 - 0s - loss: 0.0601 - acc: 0.9908
Epoch 38/43
 - 0s - loss: 0.0612 - acc: 0.9877
Epoch 39/43
 - 0s - loss: 0.0545 - acc: 0.9969
Epoch 40/43
 - 0s - loss: 0.0549 - acc: 0.9938
Epoch 41/43
 - 0s - loss: 0.0486 - acc: 0.9938
Epoch 42/43
 - 0s - loss: 0.0459 - acc: 0.9938
Epoch 43/43
 - 0s - loss: 0.0430 - acc: 1.0000

In [15]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 0.6299142661171222, Accuracy: 0.7981651387083422

In [16]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\OI\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [17]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels    : {list(y_test[:10])}")

Predicted classes: ['REP' 'REP' 'DEM' 'REP' 'DEM' 'DEM' 'DEM' 'DEM' 'DEM' 'DEM']
Actual Labels    : ['REP', 'REP', 'DEM', 'REP', 'DEM', 'DEM', 'DEM', 'REP', 'DEM', 'DEM']

In [21]:
election_dataset_minus_label = election_dataset_restricted.drop(['party'], axis=1)
election_dataset_minus_label.head(1)

,Agriculture__forestry__fishing_and_hunting__and_mining,100_000_to_149_999a,American,Less_than_50_000,Public_transportation_excluding_taxicab,ScotchIrish,50_000_to_99_999,Civilian_veterans,Mining__quarrying__and_oil_and_gas_extraction2,Unemployed,...,150_000_to_199_999,400_to_599,Abroad,Born_in_PR__US_Is_areas_or_abroad_to_US_parents,Graduate_or_professional_degree,Median_dollars1,Moved_in_2000_to_2009,Occupied_units_paying_rent,Same_state,Some_other_race
0,15248,10374,21878,11347,5827,10665,6983,64057,1447939,28267,...,18203,13275,6703,19529,52240,273100,62825,84396,16924,11279

In [22]:
all_values_list = election_dataset_minus_label.values.tolist()
all_values_scaled = X_scaler.transform(all_values_list)
all_values_a = np.array(all_values_scaled)

In [23]:
all_values_probabilities = model.predict(all_values_scaled, verbose=0)
all_values_probabilities

array([[1.08913161e-01, 8.91086876e-01],
       [1.13847770e-03, 9.98861551e-01],
       [9.58258752e-05, 9.99904156e-01],
       [1.95935514e-04, 9.99804080e-01],
       [2.28834469e-05, 9.99977112e-01],
       [4.74402659e-05, 9.99952555e-01],
       [4.28276509e-03, 9.95717227e-01],
       [9.96635139e-01, 3.36488686e-03],
       [3.34672426e-04, 9.99665380e-01],
       [1.56423391e-03, 9.98435795e-01],
       [8.50104820e-03, 9.91499007e-01],
       [5.18237241e-04, 9.99481738e-01],
       [2.88714096e-02, 9.71128643e-01],
       [9.55321133e-01, 4.46788557e-02],
       [9.99804676e-01, 1.95342320e-04],
       [1.87212334e-03, 9.98127878e-01],
       [1.70647050e-03, 9.98293579e-01],
       [1.26703680e-01, 8.73296380e-01],
       [9.99994874e-01, 5.13604482e-06],
       [4.17104410e-03, 9.95828927e-01],
       [9.99798477e-01, 2.01485789e-04],
       [5.98733546e-03, 9.94012654e-01],
       [9.78321612e-01, 2.16783471e-02],
       [9.99998569e-01, 1.46173306e-06],
       [1.00000000e+00, 2.14395968e-09],
       [1.00000000e+00, 6.85997426e-10],
       [9.99999881e-01, 9.42280778e-08],
       [9.99975204e-01, 2.48480392e-05],
       [9.99997020e-01, 2.98404143e-06],
       [9.99997854e-01, 2.17851425e-06],
       [1.00000000e+00, 2.12973458e-10],
       [9.99999046e-01, 9.94102606e-07],
       [9.99565065e-01, 4.34873305e-04],
       [9.99998331e-01, 1.63294806e-06],
       [9.84457076e-01, 1.55428890e-02],
       [9.99028444e-01, 9.71579400e-04],
       [1.83207765e-02, 9.81679201e-01],
       [9.96301293e-01, 3.69867147e-03],
       [9.80893016e-01, 1.91070046e-02],
       [9.43280220e-01, 5.67197762e-02],
       [9.99937057e-01, 6.28911148e-05],
       [1.00000000e+00, 4.99315611e-08],
       [9.99999881e-01, 6.84612544e-08],
       [9.96409237e-01, 3.59077286e-03],
       [9.99996066e-01, 3.90016112e-06],
       [9.99999285e-01, 6.70216821e-07],
       [9.99998450e-01, 1.54545035e-06],
       [1.00000000e+00, 1.16948389e-08],
       [1.00000000e+00, 1.38018111e-10],
       [1.00000000e+00, 2.64038214e-09],
       [9.97715235e-01, 2.28472846e-03],
       [1.00000000e+00, 1.10566119e-10],
       [9.99999404e-01, 5.42894270e-07],
       [9.99913692e-01, 8.62524539e-05],
       [1.62962556e-01, 8.37037504e-01],
       [1.00000000e+00, 8.85038209e-10],
       [1.00000000e+00, 1.51579777e-10],
       [9.89242852e-01, 1.07571734e-02],
       [1.00000000e+00, 1.81590512e-08],
       [1.00000000e+00, 2.29624941e-09],
       [9.99965072e-01, 3.49741567e-05],
       [9.99999642e-01, 3.93992735e-07],
       [9.99921918e-01, 7.80576374e-05],
       [9.99439776e-01, 5.60170156e-04],
       [9.99919534e-01, 8.04924202e-05],
       [9.99839306e-01, 1.60662195e-04],
       [1.17677577e-01, 8.82322431e-01],
       [9.99999642e-01, 3.60226778e-07],
       [9.99999881e-01, 7.55447545e-08],
       [9.99992251e-01, 7.80566825e-06],
       [1.00000000e+00, 5.42959064e-08],
       [9.89671171e-01, 1.03288740e-02],
       [9.23945069e-01, 7.60549009e-02],
       [9.99381065e-01, 6.18958496e-04],
       [9.99999523e-01, 4.25558596e-07],
       [9.98889983e-01, 1.11008354e-03],
       [9.32633784e-03, 9.90673602e-01],
       [1.19292215e-02, 9.88070726e-01],
       [9.03784692e-01, 9.62152928e-02],
       [9.99448955e-01, 5.50990109e-04],
       [9.33085263e-01, 6.69147596e-02],
       [9.99917150e-01, 8.28984048e-05],
       [9.73058283e-01, 2.69417036e-02],
       [9.99703825e-01, 2.96154962e-04],
       [9.99999166e-01, 8.10765073e-07],
       [9.97920454e-01, 2.07955413e-03],
       [1.02253340e-03, 9.98977542e-01],
       [3.72212240e-03, 9.96277869e-01],
       [9.99540567e-01, 4.59422154e-04],
       [1.44460966e-04, 9.99855518e-01],
       [9.59803117e-04, 9.99040186e-01],
       [4.24712926e-01, 5.75287044e-01],
       [9.98770654e-01, 1.22931274e-03],
       [4.36779950e-03, 9.95632231e-01],
       [4.31571668e-03, 9.95684266e-01],
       [7.78971116e-06, 9.99992251e-01],
       [7.67646506e-02, 9.23235357e-01],
       [4.89233015e-03, 9.95107651e-01],
       [7.85516386e-06, 9.99992132e-01],
       [9.98670697e-01, 1.32933469e-03],
       [9.30082262e-01, 6.99177906e-02],
       [9.97086704e-01, 2.91329739e-03],
       [9.84272003e-01, 1.57279391e-02],
       [9.99959826e-01, 4.02174264e-05],
       [2.05090716e-02, 9.79490936e-01],
       [9.82693553e-01, 1.73065178e-02],
       [9.99987721e-01, 1.22302790e-05],
       [1.01108616e-03, 9.98988926e-01],
       [7.65393907e-03, 9.92346048e-01],
       [9.99734342e-01, 2.65607581e-04],
       [1.66051683e-03, 9.98339415e-01],
       [9.93568778e-01, 6.43120660e-03],
       [1.92376866e-03, 9.98076200e-01],
       [9.89690781e-01, 1.03092296e-02],
       [1.33113498e-02, 9.86688673e-01],
       [7.08869848e-05, 9.99929070e-01],
       [1.00756936e-01, 8.99243057e-01],
       [2.31047422e-01, 7.68952549e-01],
       [9.99952793e-01, 4.71756721e-05],
       [3.97405165e-05, 9.99960303e-01],
       [9.90677238e-01, 9.32278391e-03],
       [1.37396288e-04, 9.99862552e-01],
       [9.99927878e-01, 7.21364777e-05],
       [1.00000000e+00, 2.93629787e-09],
       [9.98501062e-01, 1.49893528e-03],
       [3.19063663e-02, 9.68093634e-01],
       [3.79493879e-03, 9.96205032e-01],
       [9.26403081e-05, 9.99907374e-01],
       [9.99535561e-01, 4.64436336e-04],
       [9.99538541e-01, 4.61430958e-04],
       [7.31143594e-01, 2.68856347e-01],
       [6.97837412e-01, 3.02162588e-01],
       [8.21155965e-01, 1.78844064e-01],
       [3.50981683e-01, 6.49018288e-01],
       [3.73455789e-03, 9.96265471e-01],
       [1.23071449e-03, 9.98769224e-01],
       [9.99993801e-01, 6.24287759e-06],
       [9.95002925e-01, 4.99701826e-03],
       [9.78379488e-01, 2.16205791e-02],
       [5.09036005e-01, 4.90963966e-01],
       [1.10121615e-01, 8.89878392e-01],
       [9.19937491e-01, 8.00624862e-02],
       [1.38970716e-02, 9.86102939e-01],
       [1.64535716e-01, 8.35464299e-01],
       [9.54581439e-01, 4.54184897e-02],
       [5.01795337e-02, 9.49820459e-01],
       [9.99998212e-01, 1.75830621e-06],
       [9.68553483e-01, 3.14464569e-02],
       [9.99999762e-01, 2.75378341e-07],
       [9.99888420e-01, 1.11552195e-04],
       [9.92237270e-01, 7.76277296e-03],
       [1.00000000e+00, 3.02661398e-08],
       [9.89678502e-01, 1.03214420e-02],
       [9.87472296e-01, 1.25277070e-02],
       [9.29942012e-01, 7.00579807e-02],
       [4.36752141e-02, 9.56324816e-01],
       [5.96662099e-03, 9.94033396e-01],
       [5.98845189e-04, 9.99401212e-01],
       [2.52733612e-03, 9.97472584e-01],
       [3.95587267e-04, 9.99604404e-01],
       [9.94961619e-01, 5.03841275e-03],
       [1.60497278e-02, 9.83950257e-01],
       [1.02050568e-03, 9.98979509e-01],
       [5.26281912e-03, 9.94737208e-01],
       [1.68180153e-01, 8.31819832e-01],
       [9.20005143e-01, 7.99947977e-02],
       [1.26608774e-01, 8.73391211e-01],
       [8.20408059e-06, 9.99991775e-01],
       [1.50989945e-05, 9.99984860e-01],
       [2.58616745e-01, 7.41383255e-01],
       [5.52429934e-04, 9.99447525e-01],
       [5.03379169e-07, 9.99999523e-01],
       [3.55170021e-04, 9.99644876e-01],
       [1.68776680e-02, 9.83122289e-01],
       [9.99971509e-01, 2.84956495e-05],
       [7.57484650e-03, 9.92425203e-01],
       [3.30385077e-03, 9.96696115e-01],
       [4.90832084e-04, 9.99509215e-01],
       [6.09925133e-04, 9.99390006e-01],
       [9.29126680e-01, 7.08733797e-02],
       [9.86663580e-01, 1.33363856e-02],
       [9.98632610e-01, 1.36741763e-03],
       [9.99880314e-01, 1.19706863e-04],
       [9.99997854e-01, 2.18875812e-06],
       [9.99502897e-01, 4.97126777e-04],
       [1.00000000e+00, 1.32852362e-09],
       [9.99993920e-01, 6.02873843e-06],
       [9.98764634e-01, 1.23540731e-03],
       [4.48708683e-02, 9.55129147e-01],
       [9.98297155e-01, 1.70287408e-03],
       [9.99968171e-01, 3.18490493e-05],
       [1.00000000e+00, 2.48982417e-08],
       [9.99780357e-01, 2.19709415e-04],
       [9.93478656e-01, 6.52135909e-03],
       [9.99961376e-01, 3.86781430e-05],
       [9.99998927e-01, 1.02738557e-06],
       [9.84524548e-01, 1.54754920e-02],
       [5.84952354e-01, 4.15047646e-01],
       [2.44539957e-02, 9.75546002e-01],
       [2.47823689e-02, 9.75217700e-01],
       [7.78755426e-01, 2.21244559e-01],
       [9.99827385e-01, 1.72600019e-04],
       [1.00000000e+00, 3.00360337e-09],
       [9.99999881e-01, 1.19071053e-07],
       [6.37736991e-02, 9.36226249e-01],
       [9.88765210e-02, 9.01123464e-01],
       [2.26454474e-02, 9.77354586e-01],
       [9.99538898e-01, 4.61067801e-04],
       [6.11207858e-02, 9.38879251e-01],
       [1.74684767e-02, 9.82531607e-01],
       [8.62328470e-01, 1.37671515e-01],
       [9.92350280e-01, 7.64965499e-03],
       [1.04932606e-01, 8.95067334e-01],
       [2.33956993e-01, 7.66042948e-01],
       [8.38436306e-01, 1.61563724e-01],
       [9.92674291e-01, 7.32571818e-03],
       [9.99963164e-01, 3.67815337e-05],
       [1.06557729e-02, 9.89344239e-01],
       [7.08100975e-01, 2.91899025e-01],
       [3.44596393e-02, 9.65540349e-01],
       [9.99375045e-01, 6.24971930e-04],
       [4.75048482e-01, 5.24951458e-01],
       [3.72872571e-04, 9.99627113e-01],
       [6.00148749e-04, 9.99399900e-01],
       [6.42609417e-01, 3.57390523e-01],
       [1.28196031e-02, 9.87180412e-01],
       [2.69222376e-03, 9.97307777e-01],
       [6.27431000e-05, 9.99937296e-01],
       [2.34228652e-03, 9.97657657e-01],
       [9.99870420e-01, 1.29517401e-04],
       [5.26973345e-05, 9.99947309e-01],
       [2.10733378e-05, 9.99978900e-01],
       [2.92500807e-03, 9.97074962e-01],
       [9.37827706e-01, 6.21722713e-02],
       [1.05519088e-04, 9.99894500e-01],
       [8.33961076e-06, 9.99991655e-01],
       [9.83341813e-01, 1.66581012e-02],
       [2.22964748e-03, 9.97770429e-01],
       [5.78381866e-03, 9.94216204e-01],
       [5.24672854e-04, 9.99475300e-01],
       [9.99449909e-01, 5.50106983e-04],
       [5.98589795e-05, 9.99940157e-01],
       [3.38251307e-03, 9.96617496e-01],
       [2.83407397e-04, 9.99716580e-01],
       [1.63986289e-03, 9.98360097e-01],
       [6.59091445e-03, 9.93409157e-01],
       [3.12072299e-02, 9.68792796e-01],
       [2.36383975e-02, 9.76361632e-01],
       [1.25080794e-01, 8.74919176e-01],
       [9.60839272e-01, 3.91607508e-02],
       [9.59158123e-01, 4.08418477e-02],
       [9.88239169e-01, 1.17607880e-02],
       [1.00000000e+00, 2.06653183e-08],
       [9.98660922e-01, 1.33902975e-03],
       [9.97216344e-01, 2.78369151e-03],
       [9.73650992e-01, 2.63489522e-02],
       [1.55843511e-01, 8.44156504e-01],
       [9.55184773e-02, 9.04481471e-01],
       [9.94336545e-01, 5.66344615e-03],
       [9.99167323e-01, 8.32709251e-04],
       [9.98584867e-01, 1.41509552e-03],
       [1.00000000e+00, 1.65340044e-08],
       [9.99947906e-01, 5.20520407e-05],
       [9.89586949e-01, 1.04130255e-02],
       [9.33935523e-01, 6.60644546e-02],
       [9.94975448e-01, 5.02453884e-03],
       [9.99999404e-01, 5.59055991e-07],
       [5.65849282e-02, 9.43415046e-01],
       [4.53499675e-01, 5.46500385e-01],
       [9.96447027e-01, 3.55301378e-03],
       [6.81484580e-01, 3.18515450e-01],
       [1.00000000e+00, 2.40267278e-10],
       [9.88668859e-01, 1.13310963e-02],
       [1.00000000e+00, 3.62776486e-14],
       [1.00000000e+00, 1.00107734e-13],
       [1.00000000e+00, 2.99183220e-08],
       [1.00000000e+00, 2.92902584e-13],
       [1.00000000e+00, 4.03165012e-09],
       [9.99999404e-01, 5.45364344e-07],
       [9.79312062e-01, 2.06879321e-02],
       [7.84637332e-01, 2.15362653e-01],
       [9.95376706e-01, 4.62325988e-03],
       [9.87050295e-01, 1.29497200e-02],
       [9.01697204e-02, 9.09830272e-01],
       [5.70323467e-01, 4.29676622e-01],
       [3.58273923e-01, 6.41726017e-01],
       [1.91200867e-01, 8.08799207e-01],
       [7.53648162e-01, 2.46351883e-01],
       [9.81876612e-01, 1.81233790e-02],
       [1.76557526e-01, 8.23442519e-01],
       [9.99938965e-01, 6.10448187e-05],
       [9.99992490e-01, 7.54865823e-06],
       [1.00000000e+00, 4.08107468e-08],
       [9.96213496e-01, 3.78650776e-03],
       [1.00000000e+00, 4.38603536e-08],
       [1.00000000e+00, 1.54792623e-08],
       [1.00000000e+00, 1.97980121e-08],
       [4.34983484e-02, 9.56501603e-01],
       [9.83344540e-02, 9.01665568e-01],
       [9.99953866e-01, 4.61489981e-05],
       [5.54964505e-02, 9.44503546e-01],
       [8.54267240e-01, 1.45732775e-01],
       [1.03524635e-02, 9.89647567e-01],
       [1.99450031e-02, 9.80054975e-01],
       [2.22773571e-02, 9.77722645e-01],
       [1.39958849e-02, 9.86004055e-01],
       [9.93583143e-01, 6.41680742e-03],
       [1.08899428e-02, 9.89110112e-01],
       [3.18150111e-02, 9.68184948e-01],
       [1.05711417e-02, 9.89428818e-01],
       [1.33327665e-02, 9.86667216e-01],
       [3.10417800e-03, 9.96895790e-01],
       [9.94498312e-01, 5.50174713e-03],
       [1.37073174e-01, 8.62926781e-01],
       [2.18327926e-03, 9.97816682e-01],
       [1.86852019e-04, 9.99813139e-01],
       [2.75232160e-04, 9.99724805e-01],
       [9.17174160e-01, 8.28258246e-02],
       [9.97164309e-01, 2.83566117e-03],
       [1.32880896e-01, 8.67119074e-01],
       [9.99858260e-01, 1.41741417e-04],
       [8.81448805e-01, 1.18551195e-01],
       [8.33001614e-01, 1.66998342e-01],
       [1.37983561e-01, 8.62016439e-01],
       [4.76147868e-02, 9.52385187e-01],
       [5.77031896e-02, 9.42296803e-01],
       [8.66881907e-01, 1.33118093e-01],
       [2.11278439e-01, 7.88721621e-01],
       [8.95686448e-02, 9.10431385e-01],
       [6.58251420e-02, 9.34174836e-01],
       [5.69647402e-02, 9.43035245e-01],
       [7.79167593e-01, 2.20832422e-01],
       [9.88257468e-01, 1.17425583e-02],
       [9.99703825e-01, 2.96199898e-04],
       [8.25742722e-01, 1.74257308e-01],
       [5.45544177e-03, 9.94544506e-01],
       [5.39258957e-01, 4.60741043e-01],
       [9.68237936e-01, 3.17620747e-02],
       [9.91808355e-01, 8.19164421e-03],
       [9.88860667e-01, 1.11392960e-02],
       [1.74060822e-01, 8.25939119e-01],
       [9.98074889e-01, 1.92508288e-03],
       [9.81793761e-01, 1.82062779e-02],
       [8.51497471e-01, 1.48502558e-01],
       [3.32885364e-04, 9.99667168e-01],
       [7.67041420e-05, 9.99923348e-01],
       [1.72884334e-02, 9.82711613e-01],
       [7.94446532e-05, 9.99920607e-01],
       [9.98438299e-01, 1.56170980e-03],
       [2.73545575e-03, 9.97264504e-01],
       [1.47015959e-01, 8.52984071e-01],
       [1.17926209e-06, 9.99998808e-01],
       [6.78109063e-04, 9.99321938e-01],
       [6.82358805e-04, 9.99317646e-01],
       [1.94898050e-04, 9.99805152e-01],
       [4.97330278e-02, 9.50266957e-01],
       [3.46335255e-05, 9.99965310e-01],
       [4.90533930e-05, 9.99950886e-01],
       [4.94541950e-04, 9.99505401e-01],
       [9.99999404e-01, 6.51120956e-07],
       [1.24160897e-05, 9.99987602e-01],
       [7.86085367e-01, 2.13914633e-01],
       [3.93795199e-05, 9.99960661e-01],
       [4.99557750e-03, 9.95004475e-01],
       [1.03511650e-03, 9.98964906e-01],
       [2.84234378e-02, 9.71576631e-01],
       [7.82046974e-01, 2.17952996e-01],
       [9.98725951e-01, 1.27408479e-03],
       [2.27802489e-02, 9.77219760e-01],
       [9.98557150e-01, 1.44288654e-03],
       [1.55130940e-04, 9.99844790e-01],
       [6.40231892e-02, 9.35976803e-01],
       [9.85419154e-01, 1.45808589e-02],
       [9.51793373e-01, 4.82066274e-02],
       [6.87285215e-02, 9.31271434e-01],
       [4.58162390e-02, 9.54183757e-01],
       [9.99584258e-01, 4.15791554e-04],
       [5.31820056e-04, 9.99468148e-01],
       [6.98278993e-02, 9.30172086e-01],
       [2.86037065e-02, 9.71396267e-01],
       [4.30889279e-01, 5.69110751e-01],
       [9.95669484e-01, 4.33045719e-03],
       [5.34632616e-02, 9.46536720e-01],
       [9.99970794e-01, 2.92206096e-05],
       [8.88747200e-02, 9.11125243e-01],
       [9.86031294e-01, 1.39687350e-02],
       [9.99886394e-01, 1.13635571e-04],
       [7.32609570e-01, 2.67390400e-01],
       [9.99949098e-01, 5.08608646e-05],
       [5.06185577e-04, 9.99493837e-01],
       [1.03305529e-05, 9.99989629e-01],
       [1.53036916e-03, 9.98469651e-01],
       [6.34654565e-03, 9.93653417e-01],
       [9.76910889e-01, 2.30891146e-02],
       [6.81148740e-05, 9.99931931e-01],
       [9.99798596e-01, 2.01383999e-04],
       [3.77027504e-03, 9.96229708e-01],
       [1.49109408e-01, 8.50890577e-01],
       [5.48461735e-01, 4.51538324e-01],
       [8.58108521e-01, 1.41891509e-01],
       [2.10626841e-01, 7.89373100e-01],
       [9.92074013e-01, 7.92601332e-03],
       [9.99593437e-01, 4.06519801e-04],
       [9.95721340e-01, 4.27858392e-03],
       [9.99981642e-01, 1.83002940e-05],
       [9.90219772e-01, 9.78023652e-03],
       [3.97062831e-04, 9.99602973e-01],
       [1.39960815e-04, 9.99860048e-01],
       [8.37171912e-01, 1.62828118e-01],
       [1.00000000e+00, 9.48018553e-09],
       [5.45082059e-08, 1.00000000e+00],
       [9.52193081e-01, 4.78069112e-02],
       [9.97901440e-01, 2.09851633e-03],
       [9.94391978e-01, 5.60810044e-03],
       [9.94249225e-01, 5.75074507e-03],
       [1.25766277e-01, 8.74233723e-01],
       [3.33502106e-02, 9.66649771e-01],
       [1.35720685e-01, 8.64279330e-01],
       [9.58258033e-01, 4.17419672e-02],
       [1.00000000e+00, 1.51078772e-09],
       [9.55145776e-01, 4.48541716e-02],
       [9.99965787e-01, 3.42542480e-05],
       [3.04647647e-02, 9.69535232e-01],
       [9.78474557e-01, 2.15254538e-02],
       [5.60845613e-01, 4.39154387e-01],
       [9.99666452e-01, 3.33549280e-04],
       [8.53164047e-02, 9.14683580e-01],
       [9.57274958e-02, 9.04272556e-01],
       [2.10402325e-01, 7.89597631e-01],
       [4.70011421e-02, 9.52998877e-01],
       [9.98282153e-03, 9.90017235e-01],
       [1.42908711e-02, 9.85709071e-01],
       [4.62990720e-03, 9.95370090e-01],
       [6.64969347e-03, 9.93350327e-01]], dtype=float32)

In [24]:
model.predict_classes(all_values_scaled, verbose=1)

434/434 [==============================] - 0s 18us/step

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [25]:
all_values_classes = model.predict_classes(all_values_scaled, verbose=1)

434/434 [==============================] - 0s 23us/step

In [26]:
all_values_labels = label_encoder.inverse_transform(all_values_classes)

C:\Users\OI\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [27]:
all_values_labels_df = pd.DataFrame(all_values_labels)
all_values_labels_df = all_values_labels_df.rename(columns={0:"Predicted Party"})
all_values_labels_df.head()

  Predicted Party
0             REP
1             REP
2             REP
3             REP
4             REP

In [30]:
all_values_probabilities_df = pd.DataFrame(all_values_probabilities)
all_values_probabilities_df = all_values_probabilities_df.rename(columns={0:"Probability of DEM", 1:"Probability of REP"})
all_values_probabilities_df.head()

   Probability of DEM  Probability of REP
0            0.108913            0.891087
1            0.001138            0.998862
2            0.000096            0.999904
3            0.000196            0.999804
4            0.000023            0.999977

In [40]:
to_be_added = election_dataset_raw[["party", "state_dist"]]
to_be_added.head(2)

  party state_dist
0   REP      AK_00
1   REP      AL_01

In [39]:
output_df_concat = pd.concat([all_values_labels_df, all_values_probabilities_df, to_be_added], axis=1)

output_df = output_df_concat.rename(columns={"party":"Actual Winning Party"})

output_df.head(2)

,Predicted Party,Probability of DEM,Probability of REP,Actual Winning Party,state_dist
0,REP,0.108913,0.891087,REP,AK_00
1,REP,0.001138,0.998862,REP,AL_01

In [33]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_4 (Dense)              (None, 80)                3440
_________________________________________________________________
dense_5 (Dense)              (None, 80)                6480
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 162
=================================================================
Total params: 10,082
Trainable params: 10,082
Non-trainable params: 0
_________________________________________________________________

In [34]:
# Establish Connection to MySQL
import pymysql
pymysql.install_as_MySQLdb()
engine = create_engine("mysql://root:$M$CK@butt.com@localhost:3306/election_prediction_db")
conn = engine.connect()

In [35]:
#check for tables
engine.table_names()

['candidate_finance',
 'district_demographic',
 'fips',
 'house_candidate',
 'neural_net_raw_output',
 'us_congress',
 'us_congress_member',
 'us_congressional_district']

In [36]:
#push data into MySQL database
output_df.to_sql(name='neural_net_restricted_output', con=engine, if_exists='append', index=False)

In [37]:
#confirm read into MySQL
pd.read_sql_query('select * from neural_net_restricted_output', con=engine).head()

,Predicted Party,Probability of DEM,Probability of REP,Actual Winning Party,state_dist
0,REP,0.108913,0.891087,REP,AK_00
1,REP,0.001138,0.998862,REP,AL_01
2,REP,0.000096,0.999904,REP,AL_02
3,REP,0.000196,0.999804,REP,AL_03
4,REP,0.000023,0.999977,REP,AL_04