In [2]:
# Matthew Berning
# Dependencies
import numpy as np
import pandas as pd

In [3]:
election_dataset = pd.read_csv('../database/data_retrieval_clean.csv')
election_dataset.head()

,st_abbrev,district,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,...,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3,Industries_not_classified4,state_dist
0,AK,0,REP,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,...,193,1128,270,2633,569,2156,1823,40,0,AK_00
1,AL,1,REP,1325140,662806,1108650.0,0.0,264612.0,10105.0,274717.0,...,111,749,144,1427,198,1331,1663,21,0,AL_01
2,AL,2,REP,2506890,2100810,451536.0,0.0,741087.0,46129.8,787217.0,...,85,578,131,1538,159,1347,1673,29,0,AL_02
3,AL,3,REP,1219670,857764,887448.0,0.0,450890.0,9667.0,460557.0,...,47,521,89,1142,94,1186,1402,21,0,AL_03
4,AL,4,REP,1487010,853026,1099490.0,0.0,430365.0,23449.0,453814.0,...,76,401,58,1548,135,1060,1440,30,0,AL_04

In [4]:
election_dataset = election_dataset.drop(['id','st_abbrev', 'district', "Industries_not_classified4", "state_dist"], axis=1)

In [5]:
election_dataset.head()

,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,Other_Committee_Contribution,Party_Committee_Contribution,...,Real_estate_and_rental_and_leasing3,Professional__scientific__and_technical_services3,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3
0,REP,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,481912.0,0.00,...,933,1960,193,1128,270,2633,569,2156,1823,40
1,REP,1325140,662806,1108650.0,0.0,264612.0,10105.0,274717.0,985650.0,663.98,...,846,1420,111,749,144,1427,198,1331,1663,21
2,REP,2506890,2100810,451536.0,0.0,741087.0,46129.8,787217.0,1628590.0,5000.00,...,561,1249,85,578,131,1538,159,1347,1673,29
3,REP,1219670,857764,887448.0,0.0,450890.0,9667.0,460557.0,742720.0,11500.00,...,462,853,47,521,89,1142,94,1186,1402,21
4,REP,1487010,853026,1099490.0,0.0,430365.0,23449.0,453814.0,1020840.0,0.00,...,385,808,76,401,58,1548,135,1060,1440,30

In [6]:
X = election_dataset.drop("party", axis=1)
y = election_dataset["party"]
print(X.shape, y.shape)

(434, 323) (434,)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

C:\Users\OI\Anaconda3\envs\PythonData\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [8]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=500, activation='relu', input_dim=323))
model.add(Dense(units=500, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [9]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=20,
    shuffle=True,
    verbose=2
)

Epoch 1/20
 - 0s - loss: 0.4750 - acc: 0.8000
Epoch 2/20
 - 0s - loss: 0.2251 - acc: 0.9138
Epoch 3/20
 - 0s - loss: 0.1254 - acc: 0.9477
Epoch 4/20
 - 0s - loss: 0.0907 - acc: 0.9631
Epoch 5/20
 - 0s - loss: 0.0343 - acc: 1.0000
Epoch 6/20
 - 0s - loss: 0.0197 - acc: 0.9938
Epoch 7/20
 - 0s - loss: 0.0306 - acc: 0.9877
Epoch 8/20
 - 0s - loss: 0.0194 - acc: 0.9938
Epoch 9/20
 - 0s - loss: 0.0119 - acc: 1.0000
Epoch 10/20
 - 0s - loss: 0.0042 - acc: 1.0000
Epoch 11/20
 - 0s - loss: 0.0037 - acc: 1.0000
Epoch 12/20
 - 0s - loss: 0.0020 - acc: 1.0000
Epoch 13/20
 - 0s - loss: 0.0015 - acc: 1.0000
Epoch 14/20
 - 0s - loss: 0.0013 - acc: 1.0000
Epoch 15/20
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 16/20
 - 0s - loss: 9.1728e-04 - acc: 1.0000
Epoch 17/20
 - 0s - loss: 8.0959e-04 - acc: 1.0000
Epoch 18/20
 - 0s - loss: 7.2057e-04 - acc: 1.0000
Epoch 19/20
 - 0s - loss: 6.4246e-04 - acc: 1.0000
Epoch 20/20
 - 0s - loss: 5.8385e-04 - acc: 1.0000

In [10]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 0.8759298372432727, Accuracy: 0.844036697794538

In [11]:
encoded_predictions = model.predict_classes(X_test_scaled[:5])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\OI\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [12]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:5])}")

Predicted classes: ['DEM' 'DEM' 'DEM' 'REP' 'DEM']
Actual Labels: ['REP', 'REP', 'DEM', 'REP', 'DEM']

In [46]:
model.predict_proba(X_test_scaled, batch_size=32, verbose=1)

109/109 [==============================] - 0s 73us/step

array([[8.45780134e-01, 1.54219881e-01],
       [9.99684453e-01, 3.15586105e-04],
       [9.98632729e-01, 1.36727828e-03],
       [2.82049033e-08, 1.00000000e+00],
       [9.99999881e-01, 8.01581663e-08],
       [1.00000000e+00, 1.17026085e-11],
       [9.99347508e-01, 6.52508927e-04],
       [3.83362494e-04, 9.99616623e-01],
       [9.99937773e-01, 6.21645595e-05],
       [9.99984980e-01, 1.50410060e-05],
       [9.99982476e-01, 1.75608093e-05],
       [3.05958429e-06, 9.99996901e-01],
       [9.99327779e-01, 6.72264781e-04],
       [2.69865734e-03, 9.97301400e-01],
       [9.98633802e-01, 1.36613729e-03],
       [7.89898075e-03, 9.92101014e-01],
       [2.70799646e-04, 9.99729216e-01],
       [1.00000000e+00, 2.76758868e-12],
       [9.99821603e-01, 1.78400878e-04],
       [2.49910045e-06, 9.99997497e-01],
       [9.99998808e-01, 1.14704324e-06],
       [4.92105864e-05, 9.99950767e-01],
       [1.84819760e-06, 9.99998093e-01],
       [1.00000000e+00, 1.57993141e-09],
       [6.17602700e-06, 9.99993801e-01],
       [9.99996543e-01, 3.47197465e-06],
       [9.99136746e-01, 8.63241730e-04],
       [9.99762833e-01, 2.37133718e-04],
       [9.99309540e-01, 6.90462184e-04],
       [9.86238897e-01, 1.37610221e-02],
       [9.99956131e-01, 4.39217838e-05],
       [2.43596995e-04, 9.99756396e-01],
       [9.99984145e-01, 1.58284129e-05],
       [1.44156942e-07, 9.99999881e-01],
       [9.99997377e-01, 2.61018772e-06],
       [9.10399258e-01, 8.96008089e-02],
       [4.66227240e-04, 9.99533772e-01],
       [4.45772574e-04, 9.99554217e-01],
       [1.00000000e+00, 5.78118033e-08],
       [1.00000000e+00, 2.47959769e-15],
       [5.48548857e-03, 9.94514585e-01],
       [9.99999404e-01, 6.20974618e-07],
       [5.70516139e-02, 9.42948341e-01],
       [1.05770817e-03, 9.98942316e-01],
       [9.99998212e-01, 1.79832523e-06],
       [1.67302132e-01, 8.32697809e-01],
       [7.37621069e-01, 2.62378931e-01],
       [9.99994874e-01, 5.06779179e-06],
       [6.18150807e-05, 9.99938130e-01],
       [3.20067167e-01, 6.79932892e-01],
       [9.99966383e-01, 3.35899676e-05],
       [9.99897957e-01, 1.02080405e-04],
       [1.26797357e-04, 9.99873161e-01],
       [9.84953642e-01, 1.50462883e-02],
       [9.99998450e-01, 1.52739858e-06],
       [9.61134613e-01, 3.88653874e-02],
       [3.19116574e-04, 9.99680877e-01],
       [9.99329209e-01, 6.70760113e-04],
       [9.88949060e-01, 1.10509247e-02],
       [9.98541832e-01, 1.45821867e-03],
       [9.22382832e-01, 7.76171312e-02],
       [5.12509951e-06, 9.99994874e-01],
       [9.99998569e-01, 1.39062502e-06],
       [9.93944228e-01, 6.05577370e-03],
       [3.54467579e-06, 9.99996424e-01],
       [9.69500065e-01, 3.04999687e-02],
       [7.22621917e-05, 9.99927759e-01],
       [3.88095623e-06, 9.99996066e-01],
       [9.93017197e-01, 6.98276144e-03],
       [6.76746713e-05, 9.99932289e-01],
       [1.00000000e+00, 1.55403210e-08],
       [1.00000000e+00, 9.35682554e-09],
       [1.00000000e+00, 5.71842875e-08],
       [9.69180703e-01, 3.08193304e-02],
       [3.17341153e-04, 9.99682665e-01],
       [1.19009972e-04, 9.99881029e-01],
       [1.07624056e-02, 9.89237547e-01],
       [9.99997616e-01, 2.42488136e-06],
       [6.03960514e-01, 3.96039546e-01],
       [8.76403719e-05, 9.99912381e-01],
       [2.71696271e-03, 9.97282982e-01],
       [9.27026570e-02, 9.07297313e-01],
       [9.99936581e-01, 6.34382886e-05],
       [1.00000000e+00, 1.39187799e-08],
       [9.87660527e-01, 1.23393945e-02],
       [1.52207363e-07, 9.99999881e-01],
       [9.92234707e-01, 7.76530430e-03],
       [9.87405002e-01, 1.25949662e-02],
       [9.99999881e-01, 8.69720438e-08],
       [9.99996185e-01, 3.84356417e-06],
       [5.38328732e-06, 9.99994636e-01],
       [1.00000000e+00, 1.49877142e-08],
       [7.90557742e-01, 2.09442288e-01],
       [1.00000000e+00, 1.55896807e-13],
       [9.99918222e-01, 8.17474065e-05],
       [9.16834455e-03, 9.90831673e-01],
       [4.75329999e-03, 9.95246708e-01],
       [5.72190732e-02, 9.42780912e-01],
       [1.12118614e-05, 9.99988794e-01],
       [1.89914852e-01, 8.10085118e-01],
       [9.99993920e-01, 6.08427990e-06],
       [9.99999642e-01, 4.10616622e-07],
       [9.99638438e-01, 3.61493498e-04],
       [1.02311369e-05, 9.99989748e-01],
       [9.99638438e-01, 3.61599028e-04],
       [8.87523353e-01, 1.12476662e-01],
       [1.00000000e+00, 2.73255360e-17],
       [9.99998927e-01, 1.04892854e-06],
       [5.59543729e-01, 4.40456301e-01]], dtype=float32)

In [16]:
election_dataset.head()

,party,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,Other_Committee_Contribution,Party_Committee_Contribution,...,Real_estate_and_rental_and_leasing3,Professional__scientific__and_technical_services3,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3
0,REP,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,481912.0,0.00,...,933,1960,193,1128,270,2633,569,2156,1823,40
1,REP,1325140,662806,1108650.0,0.0,264612.0,10105.0,274717.0,985650.0,663.98,...,846,1420,111,749,144,1427,198,1331,1663,21
2,REP,2506890,2100810,451536.0,0.0,741087.0,46129.8,787217.0,1628590.0,5000.00,...,561,1249,85,578,131,1538,159,1347,1673,29
3,REP,1219670,857764,887448.0,0.0,450890.0,9667.0,460557.0,742720.0,11500.00,...,462,853,47,521,89,1142,94,1186,1402,21
4,REP,1487010,853026,1099490.0,0.0,430365.0,23449.0,453814.0,1020840.0,0.00,...,385,808,76,401,58,1548,135,1060,1440,30

In [17]:
election_dataset_minus_label = election_dataset.drop(['party'], axis=1)

In [18]:
election_dataset_minus_label.head()

,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,Other_Committee_Contribution,Party_Committee_Contribution,Cand_Contribution,...,Real_estate_and_rental_and_leasing3,Professional__scientific__and_technical_services3,Management_of_companies_and_enterprises3,Admin_and_support_and_waste_mngmt_and_remediation_services3,Educational_services3,Health_care_and_social_assistance3,Arts__entertainment__and_recreation3,Accommodation_and_food_services3,Other_services_except_public_administration3,Industries_not_classified3
0,1041380,1159940,151165.0,0.0,513967.0,41063.9,555031.0,481912.0,0.00,0.0,...,933,1960,193,1128,270,2633,569,2156,1823,40
1,1325140,662806,1108650.0,0.0,264612.0,10105.0,274717.0,985650.0,663.98,0.0,...,846,1420,111,749,144,1427,198,1331,1663,21
2,2506890,2100810,451536.0,0.0,741087.0,46129.8,787217.0,1628590.0,5000.00,0.0,...,561,1249,85,578,131,1538,159,1347,1673,29
3,1219670,857764,887448.0,0.0,450890.0,9667.0,460557.0,742720.0,11500.00,0.0,...,462,853,47,521,89,1142,94,1186,1402,21
4,1487010,853026,1099490.0,0.0,430365.0,23449.0,453814.0,1020840.0,0.00,0.0,...,385,808,76,401,58,1548,135,1060,1440,30

In [27]:

my_cool_list = election_dataset_minus_label.values.tolist()

tester = my_cool_list[0]

In [32]:
import numpy
from numpy import array
tester_a = array(tester)

In [35]:
tester_b = numpy.reshape(tester_a, 323)

In [37]:
tester_a.reshape(-1)

array([1.0413800e+06, 1.1599400e+06, 1.5116500e+05, 0.0000000e+00,
       5.1396700e+05, 4.1063900e+04, 5.5503100e+05, 4.8191200e+05,
       0.0000000e+00, 0.0000000e+00, 1.0369400e+06, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.1970300e+03,
       0.0000000e+00, 0.0000000e+00, 2.3624000e+02, 1.1486100e+06,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 1.5000000e+03, 0.0000000e+00,
       0.0000000e+00, 1.5000000e+03, 9.8331400e+03, 1.0354400e+06,
       1.1444100e+06, 2.6972700e+05, 0.0000000e+00, 7.3979500e+05,
       3.8577600e+05, 3.5401900e+05, 5.2919000e+04, 5.4491000e+04,
       4.8746000e+04, 4.7758000e+04, 5.4320000e+04, 1.1814900e+05,
       9.7124000e+04, 8.9052000e+04, 4.9003000e+04, 4.5192000e+04,
       5.6838000e+04, 2.0163000e+04, 6.0400000e+03, 3.4500000e+01,
       5.5461400e+05, 8.3041000e+04, 6.7640500e+05, 4.7485600e+05,
       2.2107000e+04, 1.0994800e+05, 4.9385000e+04, 8.8300000e+03,
       1.1279000e+04, 6.3390000e+04, 5.1712000e+04, 2.7896000e+04,
       7.7370000e+03, 6.3600000e+02, 1.5443000e+04, 6.8808300e+05,
       6.8160800e+05, 6.6207900e+05, 3.1405600e+05, 3.4802300e+05,
       1.9529000e+04, 5.8187000e+04, 2.1878000e+04, 9.6400000e+02,
       2.5050000e+03, 7.5130000e+03, 1.1684000e+04, 5.7276000e+04,
       1.9640000e+04, 5.1780000e+03, 1.1323500e+05, 1.3460000e+03,
       2.0800000e+03, 7.2549000e+04, 1.9204000e+04, 1.1350000e+03,
       2.4308000e+04, 1.4036000e+04, 1.4870000e+03, 9.2320000e+03,
       1.0665000e+04, 1.5956000e+04, 4.9000000e+02, 6.7950000e+03,
       1.5637000e+04, 2.5790000e+03, 3.6530000e+03, 4.3070000e+03,
       1.9980000e+03, 5.3800500e+05, 6.4057000e+04, 7.1617800e+05,
       9.0398000e+04, 1.8482200e+05, 5.7550000e+03, 4.4984400e+05,
       5.3087000e+04, 8.1512000e+04, 3.1556000e+04, 7.3087400e+05,
       5.9580400e+05, 1.2836700e+05, 8.1244000e+04, 4.7123000e+04,
       1.6924000e+04, 3.0199000e+04, 6.7030000e+03, 5.7319600e+05,
       3.8985800e+05, 3.7324900e+05, 3.4498200e+05, 2.8267000e+04,
       1.6609000e+04, 1.8333800e+05, 7.6000000e+00, 3.5128200e+05,
       2.4346600e+05, 4.1554000e+04, 5.8270000e+03, 2.5829000e+04,
       1.8622000e+04, 1.5984000e+04, 1.9600000e+01, 1.2892200e+05,
       5.9915000e+04, 8.0166000e+04, 3.8802000e+04, 3.7177000e+04,
       1.5248000e+04, 2.5180000e+04, 1.2344000e+04, 5.9220000e+03,
       4.0381000e+04, 2.8841000e+04, 7.4490000e+03, 1.1111000e+04,
       2.6392000e+04, 8.5599000e+04, 3.2032000e+04, 1.5083000e+04,
       3.9400000e+04, 2.3685100e+05, 8.6175000e+04, 2.1593000e+04,
       3.6300000e+02, 3.1696800e+05, 2.5074100e+05, 6.6227000e+04,
       1.7000000e+00, 8.1000000e+00, 1.5934400e+05, 9.1397000e+04,
       2.9600000e+00, 2.6400000e+00, 8.2577000e+04, 5.2992000e+04,
       6.2825000e+04, 2.6151000e+04, 1.6851000e+04, 9.3450000e+03,
       1.1347000e+04, 6.9830000e+03, 1.0374000e+04, 1.8203000e+04,
       4.4537000e+04, 5.3198000e+04, 1.3400000e+04, 1.3020000e+03,
       2.7310000e+05, 1.0229700e+05, 5.7047000e+04, 1.0410000e+03,
       7.6180000e+03, 2.1809000e+04, 3.0631000e+04, 2.0811000e+04,
       1.0244000e+04, 1.0143000e+04, 1.8440000e+03, 6.8270000e+03,
       9.1430000e+03, 1.3275000e+04, 1.4235000e+04, 7.7520000e+03,
       5.8150000e+03, 5.9100000e+02, 8.4396000e+04, 5.2700000e+03,
       2.4502000e+04, 2.8459000e+04, 1.5650000e+04, 8.2160000e+03,
       1.7390000e+03, 5.6000000e+02, 1.2010000e+03, 7.0010000e+03,
       1.1015000e+04, 7.4260000e+03, 1.6688000e+04, 1.9733000e+04,
       2.6582000e+04, 4.6584000e+04, 3.3858000e+04, 4.9408000e+04,
       2.1169000e+04, 1.8278000e+04, 7.3181000e+04, 9.2674000e+04,
       6.1838200e+05, 4.5290900e+05, 2.4826700e+05, 9.7796000e+04,
       1.9438300e+05, 1.8722000e+04, 7.4000000e+00, 1.1000000e+01,
       1.1000000e+01, 4.0000000e+00, 6.0000000e+00, 4.0000000e+00,
       1.8000000e+01, 2.4000000e+01, 2.6000000e+01, 1.1000000e+01,
       1.5000000e+01, 1.4000000e+01, 1.6000000e+01, 1.4000000e+01,
       1.0000000e+01, 7.0000000e+00, 9.0000000e+00, 2.1000000e+01,
       1.8646100e+05, 9.3070000e+03, 1.1597000e+04, 8.0700000e+04,
       4.0414000e+04, 4.4443000e+04, 4.8156100e+05, 1.4246000e+04,
       2.5790000e+04, 1.3313200e+05, 1.2698500e+05, 4.2724000e+04,
       8.6444000e+04, 5.2240000e+04, 9.1700000e+01, 2.8800000e+01,
       2.6607200e+05, 6.4100000e+02, 1.1838000e+04, 2.0660000e+03,
       1.7022000e+04, 1.2701000e+04, 9.3060000e+03, 3.5101000e+04,
       1.8655000e+04, 6.7590000e+03, 7.6020000e+03, 4.4890000e+03,
       1.9498000e+04, 7.4770000e+03, 1.7035000e+04, 3.1050000e+03,
       4.9799000e+04, 4.5340000e+03, 2.8606000e+04, 9.7870000e+03,
       5.1000000e+01, 1.5239195e+07, 4.5422000e+04, 1.4479390e+06,
       1.9623200e+05, 1.4969370e+06, 5.8248000e+05, 5.7295100e+05,
       1.1321400e+06, 1.3567320e+06, 4.2496500e+05, 5.1652700e+05,
       2.1696000e+05, 1.3813230e+06, 7.7076800e+05, 8.5974400e+05,
       8.8059000e+04, 2.9202140e+06, 1.0963600e+05, 7.7602100e+05,
       3.4313300e+05, 1.0120000e+03, 2.1077000e+04, 4.7500000e+02,
       1.7500000e+02, 1.0700000e+02, 2.5210000e+03, 5.3200000e+02,
       7.3900000e+02, 2.4780000e+03, 1.1450000e+03, 4.0800000e+02,
       7.9200000e+02, 9.3300000e+02, 1.9600000e+03, 1.9300000e+02,
       1.1280000e+03, 2.7000000e+02, 2.6330000e+03, 5.6900000e+02,
       2.1560000e+03, 1.8230000e+03, 4.0000000e+01])

In [38]:
model.predict_proba(tester_a)

ValueError: Error when checking input: expected dense_1_input to have shape (323,) but got array with shape (1,)

In [23]:
tester

[1041380.0,
 1159940.0,
 151165.0,
 0.0,
 513967.0,
 41063.9,
 555031.0,
 481912.0,
 0.0,
 0.0,
 1036940.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4197.03,
 0.0,
 0.0,
 236.24,
 1148610.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1500.0,
 0.0,
 0.0,
 1500.0,
 9833.14,
 1035440.0,
 1144410.0,
 269727.0,
 0.0,
 739795.0,
 385776.0,
 354019.0,
 52919.0,
 54491.0,
 48746.0,
 47758.0,
 54320.0,
 118149.0,
 97124.0,
 89052.0,
 49003.0,
 45192.0,
 56838.0,
 20163.0,
 6040.0,
 34.5,
 554614.0,
 83041.0,
 676405.0,
 474856.0,
 22107.0,
 109948.0,
 49385.0,
 8830.0,
 11279.0,
 63390.0,
 51712.0,
 27896.0,
 7737.0,
 636.0,
 15443.0,
 688083.0,
 681608.0,
 662079.0,
 314056.0,
 348023.0,
 19529.0,
 58187.0,
 21878.0,
 964.0,
 2505.0,
 7513.0,
 11684.0,
 57276.0,
 19640.0,
 5178.0,
 113235.0,
 1346.0,
 2080.0,
 72549.0,
 19204.0,
 1135.0,
 24308.0,
 14036.0,
 1487.0,
 9232.0,
 10665.0,
 15956.0,
 490.0,
 6795.0,
 15637.0,
 2579.0,
 3653.0,
 4307.0,
 1998.0,
 538005.0,
 64057.0,
 716178.0,
 90398.0,
 184822.0,
 5755.0,
 449844.0,
 53087.0,
 81512.0,
 31556.0,
 730874.0,
 595804.0,
 128367.0,
 81244.0,
 47123.0,
 16924.0,
 30199.0,
 6703.0,
 573196.0,
 389858.0,
 373249.0,
 344982.0,
 28267.0,
 16609.0,
 183338.0,
 7.6,
 351282.0,
 243466.0,
 41554.0,
 5827.0,
 25829.0,
 18622.0,
 15984.0,
 19.6,
 128922.0,
 59915.0,
 80166.0,
 38802.0,
 37177.0,
 15248.0,
 25180.0,
 12344.0,
 5922.0,
 40381.0,
 28841.0,
 7449.0,
 11111.0,
 26392.0,
 85599.0,
 32032.0,
 15083.0,
 39400.0,
 236851.0,
 86175.0,
 21593.0,
 363.0,
 316968.0,
 250741.0,
 66227.0,
 1.7,
 8.1,
 159344.0,
 91397.0,
 2.96,
 2.64,
 82577.0,
 52992.0,
 62825.0,
 26151.0,
 16851.0,
 9345.0,
 11347.0,
 6983.0,
 10374.0,
 18203.0,
 44537.0,
 53198.0,
 13400.0,
 1302.0,
 273100.0,
 102297.0,
 57047.0,
 1041.0,
 7618.0,
 21809.0,
 30631.0,
 20811.0,
 10244.0,
 10143.0,
 1844.0,
 6827.0,
 9143.0,
 13275.0,
 14235.0,
 7752.0,
 5815.0,
 591.0,
 84396.0,
 5270.0,
 24502.0,
 28459.0,
 15650.0,
 8216.0,
 1739.0,
 560.0,
 1201.0,
 7001.0,
 11015.0,
 7426.0,
 16688.0,
 19733.0,
 26582.0,
 46584.0,
 33858.0,
 49408.0,
 21169.0,
 18278.0,
 73181.0,
 92674.0,
 618382.0,
 452909.0,
 248267.0,
 97796.0,
 194383.0,
 18722.0,
 7.4,
 11.0,
 11.0,
 4.0,
 6.0,
 4.0,
 18.0,
 24.0,
 26.0,
 11.0,
 15.0,
 14.0,
 16.0,
 14.0,
 10.0,
 7.0,
 9.0,
 21.0,
 186461.0,
 9307.0,
 11597.0,
 80700.0,
 40414.0,
 44443.0,
 481561.0,
 14246.0,
 25790.0,
 133132.0,
 126985.0,
 42724.0,
 86444.0,
 52240.0,
 91.7,
 28.8,
 266072.0,
 641.0,
 11838.0,
 2066.0,
 17022.0,
 12701.0,
 9306.0,
 35101.0,
 18655.0,
 6759.0,
 7602.0,
 4489.0,
 19498.0,
 7477.0,
 17035.0,
 3105.0,
 49799.0,
 4534.0,
 28606.0,
 9787.0,
 51.0,
 15239195.0,
 45422.0,
 1447939.0,
 196232.0,
 1496937.0,
 582480.0,
 572951.0,
 1132140.0,
 1356732.0,
 424965.0,
 516527.0,
 216960.0,
 1381323.0,
 770768.0,
 859744.0,
 88059.0,
 2920214.0,
 109636.0,
 776021.0,
 343133.0,
 1012.0,
 21077.0,
 475.0,
 175.0,
 107.0,
 2521.0,
 532.0,
 739.0,
 2478.0,
 1145.0,
 408.0,
 792.0,
 933.0,
 1960.0,
 193.0,
 1128.0,
 270.0,
 2633.0,
 569.0,
 2156.0,
 1823.0,
 40.0]

In [24]:
ynew = model.predict_classes(tester)

ynew

ValueError: Error when checking input: expected dense_1_input to have shape (323,) but got array with shape (1,)